### ISSUE TITLE
Implement replicator dynamics using Python API

### ISSUE THREAD

**Issue by tturocy** [gambitproject/gambit#15]
The replicator dynamics are a simple model of evolution of strategies in a game setting as a function of the fitness of strategies, measured by their expected payoffs.  Write a simple model that carries out simulation of the replicator dynamics using the Python API.

**Comment by darkcoderrises** [comment]
Hi, i am new here. Can anyone suggest me a reading material for this and mentor me on this?

**Comment by sandeepkrjha** [comment]
Hi, I am working on this issue. should I write a two player model with their payoffs and then using replicator equation-model to predict the future behaviour?
