### ISSUE TITLE
Python extension does not work on Mac OS X Yosemite or Ubuntu Linux

### ISSUE THREAD

**Issue by cniedotus** [gambitproject/gambit#156]
Both Mac OS X and Ubuntu Linux 12.04 are 64 bit. Therefore, I use 

./configure --disable-enumpoly --disable-gui

As indicated in the document INSTALL. I tried both the commit of "57e2cb061f8ba1767b3b5bdfcfb01ad06f0327cd" on GitHub and version 14.1.0 download from sourceforge.

After finishing the steps, the command line tool of gambit works on both platforms. However, the Python extension does not.

> > > import gambit
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "gambit/**init**.py", line 23, in <module>
> > >     import gambit.lib.libgambit
> > > ImportError: No module named libgambit

I found the problem is probably from the "python setup.py build" step where some warnings show up:

On Mac:

> > > /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I../.. -I.. -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c gambit/lib/libgambit.cpp -o build/temp.macosx-10.10-x86_64-2.7/gambit/lib/libgambit.o
> > > gambit/lib/libgambit.cpp:52244:32: warning: unused function '__Pyx_PyUnicode_FromString' [-Wunused-function]
> > > static CYTHON_INLINE PyObject\* __Pyx_PyUnicode_FromString(const char\* c_str) {
> > >                                ^
> > > gambit/lib/libgambit.cpp:424:29: warning: unused function '__Pyx_Py_UNICODE_strlen' [-Wunused-function]
> > > static CYTHON_INLINE size_t __Pyx_Py_UNICODE_strlen(const Py_UNICODE *u)

On Ubuntu Linux:

> > > x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I../.. -I.. -I/usr/include/python2.7 -c gambit/lib/libgambit.cpp -o build/temp.linux-x86_64-2.7/gambit/lib/libgambit.o
> > > cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]

Anyone meets the same issue?

**Comment by enfascination** [comment]
Damn, that did it.

**Comment by Farah-Oubelkas** [comment]
I always get this error : 
AttributeError: module 'gambit' has no attribute 'Game'

Whenever I run these lines of code : 
import gambit
g = gambit.Game.new_tree()

I also can't get print(gambit.__version__), it says : module 'gambit' has no attribute '__version__'

**Comment by rahulsavani** [comment]
For the version, it should be gambit.__version__.

**Comment by WentaoYe-com** [comment]
I meet the same problem that "ImportError: No module named libgambit", any help please?
