### ISSUE TITLE
installing gambit

### ISSUE THREAD

**Issue by harveyslederman** [gambitproject/gambit#162]
I am writing with a much more basic question. I am fairly inexperienced but I have asked a number of more experienced people to help, and we have been unable to resolve this issue. We've installed the dependencies, but are getting a config.h error when attempting to build the gambit library. What are we doing wrong? Is there a place where I can find more basic step-by-step instructions? I recognize that this is a very basic question, but it has also been a very frustrating one!

Here is the error message:
2 errors generated.
error: command '/usr/bin/clang' failed with exit status 1
172-16-226-146:python hsl306$ python setup.py build
running build
running build_py
running build_ext
skipping 'gambit/lib/libgambit.cpp' Cython extension (up-to-date)
building 'gambit.lib.libgambit' extension
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I../.. -I.. -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c gambit/lib/libgambit.cpp -o build/temp.macosx-10.10-x86_64-2.7/gambit/lib/libgambit.o
In file included from gambit/lib/libgambit.cpp:247:
../libgambit/libgambit.h:30:11: fatal error: 'config.h' file not found
 #include <config.h>
          ^
1 error generated.
error: command '/usr/bin/clang' failed with exit status 1

**Comment by tturocy** [comment]
Yes, you can find build instructions in the documentation: http://gambit-project.org/gambit14/build.html .
