### ISSUE TITLE
Getting script /contrib/scripts/enumpoly/enumpoly.py to work

### ISSUE THREAD

**Issue by luke777** [gambitproject/gambit#165]
The readme in /contrib/scripts/enumpoly suggests that the script /contrib/scripts/enumpoly/enumpoly.py is more reliable than gambit-enumpoly.  Is this still the case or has  gambit-enumpoly been updated since?

I am having some trouble getting enumpoly.py to work.  It seems the python extension has changed since the script was written.

**Comment by tturocy** [comment]
That script won't have been looked at in years.  I won't be surprised it's not up-to-date.

That approach is one of those approaches which works great in theory, but will require a lot of implementation work to be reliable in practice.  gambit-enumpoly definitely is not at all completely reliable. I'm also less certain using external polynomial solvers, as the Python script does, is reliable either. The last I checked - which was several years ago - they all struggled with singular systems, but unfortunately games which are of practical interest tend to generate singular systems!
