### ISSUE TITLE
Can't build the Python Extension

### ISSUE THREAD

**Issue by cptanalatriste** [gambitproject/gambit#166]
I'm trying to build the Python extension on my Windows 10  (64 bits) system that already has Anaconda installed. So far I did the following, trying to follow the instructions published here (http://gambit-project.org/gambit14/build.html):

1. I downloaded the sources from Github
2. I downloaded and installed the Microsoft Visual C++ Compiler for Python 2.7.
3. I executed `python setup.py build`

After that, I got the following error message:

```
../libgambit\integer.cc(1427) : error C2668: 'Gambit::abs' : ambiguous call to overloaded function
        c:\users\cgavi\documents\github\gambit\src\libgambit\rational.h(84): could be 'Gambit::Rational Gambit::abs(const Gambit::Rational &)'
        c:\users\cgavi\documents\github\gambit\src\libgambit\integer.h(243): or       'Gambit::Integer Gambit::abs(const Gambit::Integer &)'
        while trying to match the argument list '(long)'
../libgambit\integer.cc(1427) : error C2228: left of '.as_long' must have class/struct/union
../libgambit\integer.cc(2151) : warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data
error: command 'C:\\Users\\cgavi\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2
```

Any ideas on how to solve this?

**Comment by tturocy** [comment]
Microsoft Visual C++ is not a supported compiler; only gcc or llvm-based compilers are tested by the development team.

**Comment by cptanalatriste** [comment]
But Cython requires the MS C++ compiler to work on Windows ...

https://github.com/cython/cython/wiki/CythonExtensionsOnWindows

**Comment by tturocy** [comment]
That's unfortunate. We don't use Windows, as it's not really a suitable environment for research computing.

**Comment by tturocy** [comment]
For further reference should anyone find this - it is not the case that Cython requires the Microsoft C++ compiler.  But, one does need to build the extension with the same compiler your Python binary was built with.  One might be better off using e.g. the Python distributed via conda than the stock Python binary.

**Comment by cptanalatriste** [comment]
I change my laptop and I'm facing the issue again:

```
$ python setup.py build
running build
running build_py
running build_ext
skipping 'gambit/lib\libgambit.cpp' Cython extension (up-to-date)
building 'gambit.lib.libgambit' extension
error: Microsoft Visual C++ 9.0 is required (Unable to find vcvarsall.bat). Get it from http://aka.ms/vcpython27
```
My new laptop is a Windows 10 machine with Python provided by Anaconda. Which Python version should I use to be able to build the Python interface?

**Comment by tturocy** [comment]
Your build system can't find a suitable compiler; that's not something that's really a Gambit-related matter.

I do apologise again for being of only limited helpfulness, but we're not Windows users.

**Comment by jac0bean9** [comment]
I've run into the same issue as cptanalatriste. Perhaps a note about Python for Windows not necessarily being supported should be added to http://gambit-project.org/gambit15/build.html#for-windows-users.

Do you happen to know if there was *ever* a version of Python which could work with gambit on Windows 10? It's understandable if not, I'll just have to use command-line gambit.
