### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by mxmpolyakov** [gambitproject/gambit#167]
Dear Gambit Developers,

for some reason I cannot compile Gambit on Opensuse 13.2--I tried both Gambit 14 and Gambit 15, get error in the same place. 

I kindly ask You to check attached log files and let me know what could be wrong.

Thanks in advance
[Protocol.txt](https://github.com/gambitproject/gambit/files/133063/Protocol.txt)
[config.log.txt](https://github.com/gambitproject/gambit/files/133066/config.log.txt)

uname -r: 3.16.7-29-desktop
Opensuse 13.2

**Comment by tturocy** [comment]
wxWidgets 3.0 is not fully supported; you should use 2.8.x or 2.9.x.

**Comment by mxmpolyakov** [comment]
Dear  tturocy , 

Thanks for the prompt reply; I've recompiled everything with wxWidget 2.8.12, same error in the same place:

[config_28.log.txt](https://github.com/gambitproject/gambit/files/133592/config_28.log.txt)
[Protocol_28.txt](https://github.com/gambitproject/gambit/files/133594/Protocol_28.txt)

**Comment by mxmpolyakov** [comment]
Solved, leave comments in a hope they will be useful to others:
1) Should download wxWidgets 2.8.12 from their website, not from opensuse repository [seems problem with versioning]
2) Should --enable-unicode during configuration of wxWidgets

**Comment by tturocy** [comment]
Many thanks for this confirmation.  When I saw the error message, it appeared to me that there was some sort of problem with the wxWidgets installation.
