### ISSUE TITLE
Build error under Arch Linux 64 bit, both stable version and git head

### ISSUE THREAD

**Issue by stefanhusmann** [gambitproject/gambit#174]
Under Arch Linux x86_64, both the stable version and the git head fail with similar problems. We have to use gcc 6.1.1 here. Logs from the build processes are attached.
[makepkg-gambit.txt](https://github.com/gambitproject/gambit/files/255866/makepkg-gambit.txt)
[makepkg-gambit-git.txt](https://github.com/gambitproject/gambit/files/255867/makepkg-gambit-git.txt)

**Comment by stefanhusmann** [comment]
A workaround: comment out line 28 of .../src/liblinear/ludecomp.imp and add -std=c++03 to the CXXFLAGS.

**Comment by tturocy** [comment]
@stefanhusmann I have pushed up some commits to the maint14 branch which I believe should correct the resolution problems with std::abs.  Could you please confirm it builds correctly on your system?

**Comment by tturocy** [comment]
As I have not heard anything more, and it works for me, I'm closing this; the fix is in releases 14.1.1 and 15.1.0.
