### ISSUE TITLE
Python - LogitQRE

### ISSUE THREAD

**Issue by j-grana6** [gambitproject/gambit#175]
In line  271 of qre.py, I think:

profile = game.mixed_strategy_profile()

should be:

profile = game.mixed_behavior_profile()

since the QRE results are for behavioral profiles, not strategy profiles...unless I am missing something.

**Comment by tturocy** [comment]
The code is correct as written.  QRE on strategic games are mixed strategy profiles; behaviour profiles are defined on extensive games.
