### ISSUE TITLE
Build error under Arch Linux 64 bit,  git head

### ISSUE THREAD

**Issue by stefanhusmann** [gambitproject/gambit#176]
The most recent commit fails to build under Arch Linux 64 bit.

[makepkg-gambit-git.txt](https://github.com/gambitproject/gambit/files/298776/makepkg-gambit-git.txt)

**Comment by tturocy** [comment]
Many thanks. This should now be corrected in commit e5b4531.

**Comment by stefanhusmann** [comment]
Indeed t is fixed, thank you.
