### ISSUE TITLE
gambit-15 compilation error on windows/mingw

### ISSUE THREAD

**Issue by hros** [gambitproject/gambit#179]
file pelqhull.cc fails with errors on conversion of 'void _' to 'long int'.
the first lines of errors:
`depbase=`echo src/tools/enumpoly/pelqhull.o | sed 's|[^/]_$|.deps/&|;s|.o$||'`;\
g++ -DHAVE_CONFIG_H -I.  -I./src -I./src/labenski/include    -g -O2 -MT src/tools/enumpoly/pelqhull.o -MD -MP -MF $depbase.Tpo -c -o src/tools/enumpoly/pelqhull.o src/tools/enumpoly/pelqhull.cc &&\
mv -f $depbase.Tpo $depbase.Po
In file included from src/tools/enumpoly/pelqhull.cc:13:0:
src/tools/enumpoly/pelqhull.cc: In function 'void qh_setappend_set(setT**, setT*)':
src/tools/enumpoly/pelqhull.h:945:76: error: cast from 'void*' to 'long int' loses precision [-fpermissive]
 #define SETreturnsize_(set, size) (((size)= (long)((set)->e[(set)->maxsize]))?(--(size)):((size)= (set)->maxsize))
                                                                            ^
src/tools/enumpoly/pelqhull.cc:396:3: note: in expansion of macro 'SETreturnsize_'
   SETreturnsize_(setA, sizeA);
   ^
src/tools/enumpoly/pelqhull.cc: In function 'void qh_setcheck(setT*, const char*, int)':
src/tools/enumpoly/pelqhull.h:945:76: error: cast from 'void*' to 'long int' loses precision [-fpermissive]
 #define SETreturnsize_(set, size) (((size)= (long)((set)->e[(set)->maxsize]))?(--(size)):((size)= (set)->maxsize))
                                                                            ^
src/tools/enumpoly/pelqhull.cc:446:3: note: in expansion of macro 'SETreturnsize_'
   SETreturnsize_(set, size);
   ^
`
I am using mingw/msys components of the anaconda m2 channel.
I can complete the compilation by adding "-fpermissive" to the CPPFLAGS 
However this is not necessary when building in linux (e.g. ubuntu), and more over the python-api build process does not complete after the "-fpermissive" make

are there special dependencies or configuration flags needed for compliation

**Comment by tturocy** [comment]
Yes, you'll likely have to use -fpermissive with mingw/msys.  That is very old code which is going to be problematic with some compilers.
