### ISSUE TITLE
Gambit crash - New Install on Mac OS

### ISSUE THREAD

**Issue by wbianco** [gambitproject/gambit#199]
Hi, cannot get Gambit to run on a Mac Air (late 2015) running the Sierra (lateast) version of the OS.  Have tried versions 14, 15, and 16 of Gambit.  File downloads properly, but when I move package to Applications folder and double-click to run, it crashes with following message.  Any thoughts?

FYI, have also tried running package from disk image, also copied it into root directory and ran fro there - same result

Process:               gambit [2827]
Path:                  /Volumes/VOLUME/Gambit.app/Contents/MacOS/gambit
Identifier:            org.gambit-project.gambit
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           gambit [2827]
User ID:               501

Date/Time:             2016-09-30 16:42:29.336 -0400
OS Version:            Mac OS X 10.11.6 (15G1004)
Report Version:        11
Anonymous UUID:        A2FE27CD-E69F-BA6A-1C65-4DAA6120EECA

Sleep/Wake UUID:       79F19B60-6729-453A-91E0-524AD48AA784

Time Awake Since Boot: 28000 seconds
Time Since Wake:       3200 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/lib/libtiff.5.dylib
  Referenced from: /Volumes/VOLUME/Gambit.app/Contents/MacOS/gambit
  Reason: image not found

Binary Images:
    0x7fff6c5d0000 -     0x7fff6c607a47  dyld (360.22) <DC81CC9D-651A-3A45-8809-928282052BD3> /usr/lib/dyld
    0x7fff8dd6d000 -     0x7fff8dd7bfff  com.apple.opengl (12.1.0 - 12.1.0) <0718DB60-BA4F-3CF7-A117-10A2515D931F> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff91f80000 -     0x7fff91f80fff  com.apple.Cocoa (6.11 - 22) <807787AB-D231-3F51-A99B-A9314623C571> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff97d4a000 -     0x7fff97ef0ff7  com.apple.audio.toolbox.AudioToolbox (1.13 - 1.13) <370E95BC-956C-3962-86CC-0A14CF6A0389> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff9bed9000 -     0x7fff9bed9fff  com.apple.Carbon (154 - 157) <8F6ED602-5943-3E29-A793-BC331E2C183D> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff9e1d0000 -     0x7fff9e1d1ffb  libSystem.B.dylib (1226.10.1) <012548CD-614D-3AF0-B3B1-676F427D2CD6> /usr/lib/libSystem.B.dylib
    0x7fff9fcc1000 -     0x7fff9fd36fff  com.apple.framework.IOKit (2.0.2 - 1179.50.2) <A509D3AE-9D48-31B7-89C7-326A7A2007B2> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit

Model: MacBookAir7,2, BootROM MBA71.0166.B12, 2 processors, Intel Core i5, 1.6 GHz, 8 GB, SMC 2.27f2
Graphics: Intel HD Graphics 6000, Intel HD Graphics 6000, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E424C54424C41522D4E5444
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E424C54424C41522D4E5444
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.21.95.175.1a6)
Bluetooth: Version 4.4.6f1 17910, 3 services, 27 devices, 1 incoming serial ports
Network Service: Apple USB Ethernet Adapter, Ethernet, en3
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0256G, 251 GB
USB Device: USB 3.0 Bus
USB Device: USB3.0 Hub
USB Device: USB3.0 Hub
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB2.0 Hub
USB Device: Keyboard Hub
USB Device: Apple Keyboard
USB Device: USB2.0 Hub
USB Device: Trackball
USB Device: Polycom CX600
USB Device: Apple USB Ethernet Adapter
Thunderbolt Bus: MacBook Air, Apple Inc., 27.2

**Comment by tturocy** [comment]
Sierra isn't supported by the prebuilt binaries at this time.  A future build of Gambit 16 might do, but almost certainly not the older ones.

**Comment by wbianco** [comment]
Hmmmm…..how far back would I have to go (in terms of OS builds) to get a version that will run Gambit?  Does the error message indicate that it’s a version problem?

Thanks!


On Oct 3, 2016, at 11:21 AM, Ted Turocy <notifications@github.com<mailto:notifications@github.com>> wrote:


Sierra isn't supported by the prebuilt binaries at this time. A future build of Gambit 16 might do, but almost certainly not the older ones.

**Comment by tturocy** [comment]
It does seem indicated, both from the report, but also from e.g. Gambit 14 having been out for years, with no complaints (at least to me) of it not working.  It indicates something system-specific, and a new OS is the most common culprit.

I run all those versions just fine on El Capitan.

**Comment by wbianco** [comment]
Thanks!

---------------------------------
William Bianco
william.bianco@gmail.com
812-340-2568
---------------------------------
