### ISSUE TITLE
repeated usage of copy_tree eats up CPU and slows down overall execution

### ISSUE THREAD

**Issue by robert-7** [gambitproject/gambit#200]
# Problem

I'm currently using Gambit's Python API. Currently, I need to create many copies of a subtree over to terminal nodes (it might be important to note that this subtree gets pretty 'large'). This is where my problem originates. I notice that every successive usage of the copy_tree method gets slowed down quite noticeably to the point where the program seems to be relatively at a stand-still compared to when it started.

```
Step g: Copying 6 to 7...
Copied bst to branch # 0 in 1.23913693428 seconds
Copied bst to branch # 1 in 2.78366398811 seconds
Copied bst to branch # 2 in 4.56539201736 seconds
Copied bst to branch # 3 in 7.04705691338 seconds
Copied bst to branch # 4 in 10.0728898048 seconds
Copied bst to branch # 5 in 13.6722579002 seconds
Copied bst to branch # 6 in 17.7328939438 seconds
Copied bst to branch # 7 in 22.4001049995 seconds
...
```

I think manually creating each subtree is actually faster than copying the one subtree over. Moreover, the CPU is 100% utilized, even though the memory is barely used (can't be much more than 0.2% at any point). This can be seen with the `top` call (even after a few minutes into the execution). 

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
32662 robertl+  20   0  241512  36036   5064 R 100.0  0.0   2:07.88 python
```
# Question

My question is: is this a bug in any way or is this expected? If it is expected, then feel free to close this issue. However, providing at least one alternative/hack to speed up the process would be valuable. 

Please tell me if more details are needed.
# Specs

Here are the two OSes I've run this on:

```
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

```
NAME="Scientific Linux"
VERSION="7.2 (Nitrogen)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Scientific Linux 7.2 (Nitrogen)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:scientificlinux:scientificlinux:7.2:GA"
HOME_URL="http://www.scientificlinux.org//"
BUG_REPORT_URL="mailto:scientific-linux-devel@listserv.fnal.gov"

REDHAT_BUGZILLA_PRODUCT="Scientific Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.2
REDHAT_SUPPORT_PRODUCT="Scientific Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.2"
Scientific Linux release 7.2 (Nitrogen)
Scientific Linux release 7.2 (Nitrogen)
Scientific Linux release 7.2 (Nitrogen)
```

**Comment by tturocy** [comment]
There is internal housekeeping that's done in the extensive game data structure to keep it in a canonical form.  I am certain it could be done in a more elegant way that would improve the performance of the operations - and so I'm going to leave this open for now.  However, in most cases, the amount of time it will take to do anything interesting with the analysis of the game is going to be orders of magnitude what it takes to build it - that is, almost certainly, if the game takes too long to build, it's probably going to be too big to solve anyway.  (There are indeed exceptions of course.)
