### ISSUE TITLE
gambit.StrategySupportProfile's remove() function doesn't remove anything

### ISSUE THREAD

**Issue by robert-7** [gambitproject/gambit#201]
# Scenario
I have game tree with strategies. I call this to get me to undominated strategies:
```
undominated = g.support_profile().undominated()
```

I want to remove all the strategies NOT in this list from my game (i.e. remove all dominated strategies in the game). So I call:

```
for strategy in g.support_profile():
    if strategy not in undominated:
        g.support_profile().remove(strategy)
```

However, I think this leaves my list unchanged... (I expected to remove ~200 and remain with 3 strategies, yet I still had my ~200 strategies).

What could I possibly be doing incorrectly?

**Comment by tturocy** [comment]
Every call to g.support_profile() generates a new support profile.  So, what that call in the loop is doing is creating a new support profile, removing a strategy from it, and then discarding the support profile.

**Comment by robert-7** [comment]
Thank you. This answers this question.
