### ISSUE TITLE
an attribute "gambit.new_tree()" is missing

### ISSUE THREAD

**Issue by lampda** [gambitproject/gambit#202]
Please can you have a review of your code, or post some solution here?
Cheers,

**Comment by tturocy** [comment]
There is no gambit.new_tree().  Do you mean gambit.Game.new_tree()?  See for example the very first example in the documentation:

http://www.gambit-project.org/gambit16/16.0.0/pyapi.html

**Comment by fairsky66** [comment]
Oh, thanks for correction. However, while I was installing gambit via pip, it said it is of 0.16.0 version and while running from my code, I got this error message that indicating no gambit.new_tree().
So, I think there maybe a gap for this lib between PyPI repo and github repo.
Can you check it, please?

**Comment by tturocy** [comment]
Gambit is not in PyPI, and 0.16.0 is not a valid Gambit version number.

**Comment by drvinceknight** [comment]
FYI, the confusion might come from https://pypi.python.org/pypi/gambit which is a library that has nothing to do with gambit. (Have had this come up a couple of times.)

**Comment by fairsky66** [comment]
@drvinceknight Oh, I should have read its description, however, this might be an interesting lib for my work relevant to elasticsearch.
Cheers, all.
