### ISSUE TITLE
Removing Dominated Strategies in Strategic Game

### ISSUE THREAD

**Issue by robert-7** [gambitproject/gambit#204]
# The Problem and Attempts

I'm using Gambit's Python API to create a game tree. I have game tree with strategies and I want to reduce my tree by eliminating all strictly dominated strategies (before creating solver and solving it using:

```
solver = gambit.nash.ExternalEnumMixedSolver()
solver.solve(g)
```

The reason I want to reduce my tree is because it's taking a bit too long to solve just by itself. Also, 2 reasons why I am not just doing this in the Gambit UI is: sometimes my tree is too big for to load in UI and it won't let me save a tree that's been trimmed of dominated strategies, which annoys me.)

Anyways, I can call this to get me the undominated strategies:

```
undominated = g.support_profile().undominated()
```

However, I have no idea how to use this information (or where in the Python API Documentation) I can use this information to simply solve the game using these pure strategies. One method I tried was to create a NEW game with just these undominated strategies, but I don't think that's possible...

Could someone please advise? I'm certain this is possible, but I just don't see it anywhere in the docs.

**Comment by tturocy** [comment]
You want the `.restrict()` operation on `StrategySupportProfile`. This creates an object which is a `Game`, but with only the strategies specified in the support profile.

http://www.gambit-project.org/gambit16/16.0.0/pyapi.html#gambit.StrategySupportProfile.restrict

**Comment by robert-7** [comment]
Hmm, I noticed that this call gets really slow once my tree gets a little bigger. 

```
undominated = g.support_profile().undominated()
```

However, I feel this properly answers my question; so thank you :)

**Comment by tturocy** [comment]
In general, the number of strategies grows exponentially in the size of the game tree.  So it's going to get slower.
