### ISSUE TITLE
Compilation errors for python extension on Windows 7

### ISSUE THREAD

**Issue by Subimago** [gambitproject/gambit#205]
Hello there,

I am trying to build the python extension in this environment:
Windows 7 
Anaconda 2 (64 Bit)
MinGW (Msys)
Microsoft Visual C++ Compiler for Python 2.7
gambit 16.0.0 (also tried gambit 15 but has same issues)

To build it  i am following the instructions here: [http://www.gambit-project.org/gambit15/build.htm](http://www.gambit-project.org/gambit15/build.html)

Gambit itself has been build successfully. 
But if i execute the first command for the python extension build (**python setup.py build**) i get countless errors:

> c/gambit-16.0.0/src/python
$ python setup.py build
running build
running build_py
running build_ext
skipping 'gambit/lib\libgambit.cpp' Cython extension (up-to-date)
building 'gambit.lib.libgambit' extension
C:\Users\user\AppData\Local\Programs\Common\Microsoft\Visual C++ for Py
thon\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I../.. -I../.
./library/include -I.. "-Ic:\Program Files\Anaconda2\include" "-Ic:\Program File
s\Anaconda2\PC" /Tpgambit/lib\libgambit.cpp /Fobuild\temp.win-amd64-2.7\Release\
gambit/lib\libgambit.obj
libgambit.cpp
C:\Users\user\AppData\Local\Programs\Common\Microsoft\Visual C++ for Py
thon\9.0\VC\Include\xlocale(342) : warning C4530: C++ exception handler used, bu
t unwind semantics are not enabled. Specify /EHsc
c:\gambit-16.0.0\library\include\gambit\game.h(843) : warning C4290: C++ excepti
on specification ignored except to indicate a function is not __declspec(nothrow
)
c:\gambit-16.0.0\library\include\gambit\agg\proj_func.h(104) : warning C4267: 'r
eturn' : conversion from 'size_t' to 'int', possible loss of data
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.h(131) : error C3646: '__at
tribute__' : unknown override specifier
        c:\gambit-16.0.0\library\include\gambit\agg\trie_map.h(574) : see refere
nce to class template instantiation 'Gambit::agg::trie_map<V>' being compiled
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.h(131) : error C2059: synta
x error : '('
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.h(131) : error C2091: funct
ion returns function
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.h(131) : error C4430: missi
ng type specifier - int assumed. Note: C++ does not support default-int
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.h(131) : error C2059: synta
x error : ')'
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.h(131) : error C2143: synta
x error : missing ';' before ')'
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.h(131) : error C2238: unexp
ected token(s) preceding ';'
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.h(453) : error C2059: synta
x error : '('
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.h(453) : error C4430: missi
ng type specifier - int assumed. Note: C++ does not support default-int
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.h(453) : error C2059: synta
x error : ')'
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.h(453) : error C2143: synta
x error : missing ';' before ')'
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.h(453) : warning C4183: '__
attribute__': missing return type; assumed to be a member function returning 'in
t'
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.h(453) : error C2334: unexp
ected token(s) preceding '{'; skipping apparent function body
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.h(484) : error C2988: unrec
ognizable template declaration/definition
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.h(484) : error C2059: synta
x error : '('
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.h(484) : error C4430: missi
ng type specifier - int assumed. Note: C++ does not support default-int
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.h(484) : error C2988: unrec
ognizable template declaration/definition
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.h(484) : error C2059: synta
x error : ')'
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.h(516) : error C2238: unexp
ected token(s) preceding ';'
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.imp(32) : error C2065: 'x'
: undeclared identifier
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.imp(53) : error C2433: 'Gam
bit::agg::trie_map<V>::insert' : 'inline' not permitted on data declarations
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.imp(53) : warning C4346: 'G
ambit::agg::trie_map<V>::value_type' : dependent name is not a type
        prefix with 'typename' to indicate a type
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.imp(53) : error C2350: 'Gam
bit::agg::trie_map<V>::insert' is not a static member
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.imp(57) : error C2065: 'alw
ays_inline' : undeclared identifier
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.imp(57) : error C2448: '__a
ttribute__' : function-style initializer appears to be a function definition
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.imp(58) : error C2065: 'V'
: undeclared identifier
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.imp(58) : error C2065: 'V'
: undeclared identifier
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.imp(65) : error C2509: 'fin
d' : member function not declared in 'Gambit::agg::trie_map'
        c:\gambit-16.0.0\library\include\gambit\agg\trie_map.h(68) : see declara
tion of 'Gambit::agg::trie_map'
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.imp(70) : error C2065: 'k'
: undeclared identifier
c:\gambit-16.0.0\library\include\gambit\agg\trie_map.imp(78) : error C2433: 'Gam
bit::agg::trie_map<V>::findExact' : 'inline' not permitt
e
....

Can someone please tell me what mistakes i am doing?

**Comment by tturocy** [comment]
Building on Windows is not really supported. It can be done, but it requires using MinGW (and therefore using a Python binary built with MinGW).

**Comment by Subimago** [comment]
Ok thanks for the quick answer. I'll check if we can use some Unix environment then.
