### ISSUE TITLE
Command-Line Troubles on Windows 10

### ISSUE THREAD

**Issue by jac0bean9** [gambitproject/gambit#209]
I'm loving the package, but having some trouble using it outside of interactive mode. When I try gambit-enummixed or gambit-logit on the default Windows command prompt, I get the Gambit banner and then ... nothing. What's worse, the file which I wanted to solve gets erased, left empty.

This behavior continued when I tried swapping in 16.0.0 for 15.1.0 and for both .efg and .nfg formats. When I tried "gambit [file].nfg", Gambit does open -- but the file is emptied and Gambit has no game.

Perhaps there is just something bizarre about my computer (possibly self-inflicted from when I tried and failed to add Gambit Python functionality). Do others run into this problem? If there's no easy fix, are there any ideas for workarounds, i.e. to access Gambit's interactive mode solver via the command line?

**Comment by tturocy** [comment]
It would be helpful if you could supply the exact command line you used (see the hints in the docs on reporting bugs and seeking support).

From your description, I am guessing what you did was

gambit-enummixed > file.nfg

which would (a) overwrite file.nfg (as you have directed the output of the programme to it) and (b) would sit and wait for you to give it input (as you did not give it a file to process so it would read it from standard input).

What you would want is

gambit-enummixed file.nfg

**Comment by jac0bean9** [comment]
Yes! That works! Thank you so much!
