### ISSUE TITLE
Are you sure that gambit computes correct results?

### ISSUE THREAD

**Issue by davagin** [gambitproject/gambit#210]
I am trying to play with program. And something struck me as odd.

This is a simple game for which I am trying to find Nash equilibrium.
================= Begin ==========================
EFG 2 R "A simple Poker game" { "Fred" "Alice" }
""

c "" 1 "" { "Red" 1/2 "Black" 1/2 } 0
p "" 1 1 "" { "Raise" "Fold" } 0
p "" 2 1 "" { "Meet" "Pass" } 0
c "" 2 "" { "1" 1/2 "2" 1/2 } 0
p "" 1 2 "" { "1" "2" } 0
p "" 2 2 "" { "1" "2" } 0
t "" 1 "Win Very Big" { 3, -3 }
t "" 2 "Win Big" { 2, -2 }
t "" 3 "Lose Big" { -2, 2 }
p "" 1 3 "" { "1" "2" } 0
p "" 2 3 "" { "1" "2" } 0
t "" 4 "Lose Very Big" { -3, 3 }
t "" 2 "Win Big" { 2, -2 }
t "" 3 "Lose Big" { -2, 2 }
t "" 5 "Win" { 1, -1 }
t "" 6 "Lose" { -1, 1 }
p "" 1 4 "" { "Raise" "Fold" } 0
p "" 2 1 "" { "Meet" "Pass" } 0
c "" 3 "" { "1" 1/2 "2" 1/2 } 0
p "" 1 5 "" { "1" "2" } 0
p "" 2 2 "" { "1" "2" } 0
t "" 4 "Lose Very Big" { -3, 3 }
t "" 2 "Win Big" { 2, -2 }
t "" 3 "Lose Big" { -2, 2 }
p "" 1 6 "" { "1" "2" } 0
p "" 2 3 "" { "1" "2" } 0
t "" 1 "Win Very Big" { 3, -3 }
t "" 2 "Win Big" { 2, -2 }
t "" 3 "Lose Big" { -2, 2 }
t "" 5 "Win" { 1, -1 }
t "" 6 "Lose" { -1, 1 }
================== End =========================

The problem is following:
1. When I try to find one Nash equilibrium using recommended settings it gives to me some result.
2. When I try to find all Nash equilibria using recommended settings it gives to me 4 Nash equilibria. But they are equial between each other. And they are not equial to result computed in first step. By the way the "Computing Nash equilibria" window shows 4 Nash equilibria, and they are different to each other. The format of result in this window differs from format in "list of computed strategy profiles".

What is the problem with it? Am I doing something wrong?

**Comment by tturocy** [comment]
From your description I cannot see anything wrong. The game has a continuum of Nash equilibria, comprising a convex set with four extreme equilibria. All of those Nash equilibria have the same realisation in terms of behaviour strategy profiles, however. That all seems consistent with what you describe.
