### ISSUE TITLE
Gambit-lp Runtime error: bad pivot in LUdecomp?

### ISSUE THREAD

**Issue by Syoung177** [gambitproject/gambit#211]
I've built a sizable efg (200 info sets, ~2900 nodes) through an external Python script, and am trying to compute the Nash equilibrium with the LP method. The game is constant sum and perfect recall. I am able to import the game from a text file into the Python Gambit library with no issues, and Gambit seems to read in the info sets, payoffs, players, nodes, etc correctly. The text file that I'm using is below.

However, when I run gambit.nash.lp_solve(game, rational=False), I get the following error: 

RuntimeError: bad pivot in LUdecomp 

I cannot find any documentation of this error in the source code or anywhere else online.  I've used this command on the sample games successfully. Does anyone have any idea what may be causing this issue? This is crucial for my thesis, and would really appreciate any assistance. Thanks!

[LUdecomp.txt](https://github.com/gambitproject/gambit/files/755685/LUdecomp.txt)

**Comment by tturocy** [comment]
Using floating-point arithmetic can lead to numerical instability (in the implementation that's packaged with Gambit).  Using rational=True is strongly recommended.  However, it will take a very long time in a game of that size; it may be impractical.
