### ISSUE TITLE
Gambit 16 on macOS Sierra

### ISSUE THREAD

**Issue by EllaKaye** [gambitproject/gambit#212]
Hello. I am trying to install Gambit on a mac running macOS Sierra. I've downloaded the .dmg, but when I try and open the application, I get the following error message. What can I do to get Gambit up and running? Apologies if this is not the right place to post this question - if it isn't could you let me know where would be a better forum. Thanks.

Process:               gambit [16477]
Path:                  /Volumes/VOLUME/*/Gambit.app/Contents/MacOS/gambit
Identifier:            org.gambit-project.gambit
Version:               16.0.0 (16.0.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           gambit [16477]
User ID:               501

Date/Time:             2017-03-09 23:15:55.238 +0000
OS Version:            Mac OS X 10.12.3 (16D32)
Report Version:        12
Anonymous UUID:        59F0758E-F299-EF02-59E6-AA5EBF2AF3CA

Sleep/Wake UUID:       CD5C418B-6CC3-4777-A500-89F79AED5DB3

Time Awake Since Boot: 99000 seconds
Time Since Wake:       7800 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/libtiff/lib/libtiff.5.dylib
  Referenced from: /Volumes/VOLUME/*/Gambit.app/Contents/MacOS/gambit
  Reason: image not found

Binary Images:
       0x100000000 -        0x10081afff +org.gambit-project.gambit (16.0.0 - 16.0.0) <59E5449B-57E5-3E85-8346-F098704A506F> /var/folders/*/Gambit.app/Contents/MacOS/gambit
       0x10a5db000 -        0x10a618267  dyld (421.2) <947FC440-80F9-32F7-A773-6FC418FE1AB7> /usr/lib/dyld
    0x7fffc979d000 -     0x7fffc99adfff  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <A1B98513-C19E-376F-8DAF-71BB2F263C5F> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fffc9f04000 -     0x7fffc9f04fff  com.apple.Carbon (154 - 157) <1BF9C0EB-45A0-3584-85DC-F64A9914F40D> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fffca3b9000 -     0x7fffca3b9fff  com.apple.Cocoa (6.11 - 22) <CF1AD0E9-2257-35FE-B719-760B58E405C9> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fffcc908000 -     0x7fffcc99dff7  com.apple.framework.IOKit (2.0.2 - 1324.30.13) <163BE7FA-B29A-348F-8B5F-E301F2E8C964> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fffcf9a0000 -     0x7fffcf9aefff  com.apple.opengl (13.0.10 - 13.0.10) <B11A2E1B-4B1D-3ECD-BADA-3508BE5775BF> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fffde962000 -     0x7fffde963ff3  libSystem.B.dylib (1238) <9CB018AF-54E9-300F-82BE-81FE553C9154> /usr/lib/libSystem.B.dylib

Model: MacBookPro11,2, BootROM MBP112.0138.B21, 4 processors, Intel Core i7, 2.2 GHz, 16 GB, SMC 2.18f15
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.21.171.68.1a5)
Bluetooth: Version 5.0.3f1, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0256F, 251 GB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1

**Comment by tturocy** [comment]
Sierra is not supported by the pre-built binary. At the present moment the option is to compile from source.  This is not something I'm going to be able to get to dealing with in the short run (so any contributor willing to take this on it would be welcomed!)

**Comment by masonwright14** [comment]
We tried installing Gambit on Mac OS Sierra also, and this seemed to be a problem with the absence of Libtiff. You can get Libtiff via Homebrew by doing:

`brew install libtiff`

[http://brewformulas.org/Libtiff](url)

**Comment by drmohamad72** [comment]
I have a source code tictactoe  game in python api
