### ISSUE TITLE
malloc using gambit on a notebook

### ISSUE THREAD

**Issue by enfascination** [gambitproject/gambit#213]
I have a strange error where I can get gambit working on simple consoles, but not when there is some service connecting to another python instance (jupyter console, jupyter notebook, ipython console, jupyter qtconsole).  viz:
```
$ > ipython
Python 2.7.11 |Anaconda custom (x86_64)| (default, Dec  6 2015, 18:57:58)
Type "copyright", "credits" or "license" for more information.
IPython 4.0.3 -- An enhanced Interactive Python.
In [1]: import gambit
In [2]: g = gambit.Game.new_tree()
In [3]: g
Out[3]:
EFG 2 R "" { }
""
t "" 0
In [4]:
Do you really want to exit ([y]/n)? y
$ > 
$ > 
$ > ipython console                            Jupyter Console 4.1.0
()
In [1]: import gambit
In [2]: g = gambit.Game.new_tree()
In [3]: g
python(3599,0x7fff730f0300) malloc: *** error for object 0x106193580: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
kernel died, restart ([y]/n)? 
```

As you can see, gambit works in `ipython` but not in `ipython console` (or anything in jupyter).  Maybe I'm bad on my breakpoint skills, but I'm having trouble even diagnosing the problem (establishing whether it's gambit or ipython that's having trouble).

**Comment by tturocy** [comment]
This is tickling vague memories of having experienced a similar issue at some point.  My suspicion would be that it has to do with different versions of shared libraries, although it would seem odd this would be the case for ipython v. ipython console.
