### ISSUE TITLE
Can't build the Python Extension on Ubuntu 16

### ISSUE THREAD

**Issue by pukkinming** [gambitproject/gambit#214]
I'm trying to build the Python extension on Ubuntu. I can successfully build the command-line tools but the building of Python Extension fails.

Instead of getting a bunch of errors, I got a lot of warning like

cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
![image](https://cloud.githubusercontent.com/assets/1624820/25207311/3c9789b6-2533-11e7-85b6-f52daea801d9.png)

And in the end I couldn't import the gambit library in python2. 
![image](https://cloud.githubusercontent.com/assets/1624820/25207325/56dbfe7e-2533-11e7-9f8a-0c2a935a46dd.png)

Do u have any clues on what's going here?

**Comment by pukkinming** [comment]
Btw I just tried to import gambit library in a non-build folder, and still it doesn't work:

![image](https://cloud.githubusercontent.com/assets/1624820/25207528/01475e7a-2535-11e7-8555-da6ed172dc57.png)

**Comment by tturocy** [comment]
Could you please post the error you are getting?  The screenshot you show doesn't show any error - screenshots obviously aren't helpful because one really needs to look at the whole build trace to see what is going on.

**Comment by pukkinming** [comment]
Hi Dr. Ted, 
Most certainly. Attached please find the compressed file. I attached the whole build trace for
- building from source and
- building python extension
Building from source is smooth and error free, but I got a lot of warning on building python extension. Btw I am using Ubuntu 16 and Gambit 15.
Many thanks!
Frank

[gambit_building_history.zip](https://github.com/gambitproject/gambit/files/943741/gambit_building_history.zip)

**Comment by tturocy** [comment]
Here's your problem:

```
frank@ie-cosmos9:~/Dropbox/Toolbox/gambit15/src/python$ sudo python setup.py install
```

Everywhere else you call `python2` but here you call `python`, which is likely another installation...

**Comment by pukkinming** [comment]
Dr. Ted, I just tried "sudo python2 setup.py install", and still it doesn't work. Really sorry to bother you on this. Frank

**Comment by pukkinming** [comment]
Dr. Ted, 

Although I still can't import gambit (with python 2.7) in python shell, I found the following in /usr/local/bin/

![image](https://cloud.githubusercontent.com/assets/1624820/25249165/90bf670e-25d6-11e7-887d-9446ff0ab0cc.png)

And if I run the shell, I can still use full functionality of the Python API:
![image](https://cloud.githubusercontent.com/assets/1624820/25249265/ec1ad764-25d6-11e7-89dd-632cfd5faf10.png)

![image](https://cloud.githubusercontent.com/assets/1624820/25249286/fc5259a4-25d6-11e7-883e-5d6cd2c4a0fa.png)

My problem of importing the library is still not resolved, but at least I am managed to use the API extension. Thank you so much for your attention.

Sincerely,
Frank

**Comment by tturocy** [comment]
Again, what do you mean by "still it doesn't work."  Without a log of what you did, it's simply impossible for me even to begin to help.

However, this really looks like a problem with your Python installation; it's not a Gambit issue from what I can see.

**Comment by pukkinming** [comment]
Thank you so much Dr. Ted.

**Comment by tturocy** [comment]
Do please post the resolution if you find it - even if it is not Gambit-specific someone may encounter the issue.  Or of course if it does look like something in the Gambit setup that is having an interaction with your system, that is important to know.

**Comment by pukkinming** [comment]
Dr. Ted, I am sorry that I still couldn't find the solution so far. So my working around is to use the gambit shell as located in /usr/local/bin, and in that case I couldn't use any external library from command-line tools. I will post again if I find a solution.

**Comment by tturocy** [comment]
That is why I am very suspicious it has something to do with which installation of the Python interpreter you are installing to.

Calling gambit-shell automatically uses the Python environment that you have installed Gambit under.  So, calls to Gambit will work great.  But, if it is not the Python environment that is being access when you are running another Python script (or the interpreter from the command line), then you won't have any other libraries installed in that environment.

The trouble is, try as I might to see where you are going wrong, I can't see it from the logs.  I thought for sure the "python" versus "python2" I suggested a few comments back was the problem - it would produce exactly this sort of behaviour - but apparently not.

**Comment by drvinceknight** [comment]
The output of `which -a python` as well as `which python` might offer some
insight. (And seeing how `python3` differs etc)
