### ISSUE TITLE
What is the meaning of small- to medium-sized games supported?

### ISSUE THREAD

**Issue by pukkinming** [gambitproject/gambit#217]
In the documentation, it is stated that "the graphical interface is largely intended for the interactive construction and analysis of small to medium games". 

May I know how large a game can be regarded as a small game and a medium game in your experience?

**Comment by drmohamad72** [comment]
Hello
I'm an iranian student and need the python code of the game Tic Tac Toe.
The efg file is availabe at github with the following link. I would
appreciate if you could send me the python code.
Thanks

https://github.com/gambitproject/gambit/blob/0523d86a0cd462d253d12c077e56cf83a5ecd330/contrib/games/ttt.efg
