### ISSUE TITLE
Brushing up for the icon?

### ISSUE THREAD

**Issue by alexanderjulmer** [gambitproject/gambit#221]
Gambit is awesome but the icon could use some brushing-up. I had a bit too much time on my hand and made a sketch for OS X and I could make one for Windows, too. Sorry if it is unsolicited. 

![gambit icon draft](https://user-images.githubusercontent.com/10468332/27762564-bf0cd160-5e74-11e7-8a87-3212e26b0cb1.png)

**Comment by tturocy** [comment]
Thank you for this.

The Gambit icon looks the way it does for historical reasons - Richard McKelvey always liked the "fuzziness" of the logo as it is reflective (in his view) of the limitations in computation in games.  Therefore we have always kept it in is memory/honour.

That said the file itself is a several-generations copy of an icon that was created in the mid-1990s.  Subject to keeping the branding looking similar (and ever-so-slightly 8-bit!) certainly a freshened-up set of assets would be of some interest.

**Comment by alexanderjulmer** [comment]
I didn't expect that much history with the logo, but since I've started already, I'd certainly turn that into a 8-bit version and provide the full set of assets. Which would that actually be and what sizes are necessary?

Also from a stylistic perspective, I would reluctantly suggest to remove the text from the logo since it's most often displayed by the operation system anyways.

**Comment by tturocy** [comment]
Yes, there is a bit of emotive content to those images that wouldn't be something one would know about if one hadn't been around the project for two decades...!

The graphical assets involved in the desktop graphical interface are in src/gui/bitmaps in the repository.  There is also gambit.png in the gambit-site repository, but I believe that this is the same as the version that's in this repository.
