### ISSUE TITLE
Python Extension Install 'Python.h' file not found

### ISSUE THREAD

**Issue by timholds** [gambitproject/gambit#223]
Hello. I am trying to install the latest version of Gambit on a Mac running Sierra 10.2.6. 
Python2.7 was installed by Anaconda.

I was successful in doing all of the install steps up to "python setup.py build", which is where I am getting an error. Please note that I am actually doing "sudo /anaconda/lib/bin/python2.7 setup.py install" in order to run python2.7 instead of 3.5, which is what runs if I do the regular old "python setup.py build".

What shows up in the console when I run that:
running install
running bdist_egg
running egg_info
writing gambit.egg-info/PKG-INFO
writing top-level names to gambit.egg-info/top_level.txt
writing dependency_links to gambit.egg-info/dependency_links.txt
writing entry points to gambit.egg-info/entry_points.txt
reading manifest file 'gambit.egg-info/SOURCES.txt'
writing manifest file 'gambit.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
running build_ext
skipping 'gambit/lib/libgambit.cpp' Cython extension (up-to-date)
building 'gambit.lib.libgambit' extension
gcc -fno-strict-aliasing -I//anaconda/envs/py27/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I../.. -I../../library/include -I.. -I/anaconda/include/python2.7 -c gambit/lib/libgambit.cpp -o build/temp.macosx-10.7-x86_64-2.7/gambit/lib/libgambit.o
gambit/lib/libgambit.cpp:4:10: fatal error: 'Python.h' file not found
#include "Python.h"
         ^
1 error generated.
error: command 'gcc' failed with exit status 1

The Python.h file is available in the /System/Library/Frameworks/Python.framework/Versions/2.7/ directory, so I cannot quite figure out why I am getting this error. I have spent a few hours trying to figure it out, but so far no luck. 

Thanks for your help.

**Comment by tturocy** [comment]
This isn't a Gambit issue, but in the first instance, the conda install wouldn't be looking for Python.h in /System, but in the /anaconda install (note the include switches on the compile command).  First guess is you haven't installed python2.7-dev?
