### ISSUE TITLE
Cannot build Python extension for Gambit in Windows 10

### ISSUE THREAD

**Issue by saubhik** [gambitproject/gambit#227]
I installed MinGW (along with gcc python bindings using [this](https://github.com/develersrl/gccwinbinaries)) and successfully built gambit from source. However, I cannot build the python interface from `\src\python`. I get the following errors from running `python setup.py build` in msys:

> saubh@DESKTOP-7SU5HIM /e/gambit/gambit-master/src/python
> $ python setup.py build
> running build
> running build_py
> running build_ext
> skipping 'gambit/lib\libgambit.cpp' Cython extension (up-to-date)
> building 'gambit.lib.libgambit' extension
> C:\MinGW\bin\gcc.exe -mno-cygwin -mdll -O -Wall -I../.. -I../../library/include -I.. "-Ic:\Program Files\Python27\include" "-Ic:\Program Files\Python27\PC" -c gambit/lib\libgambit.cpp -o build\temp.win-amd64-2.7\Release\gambit\lib\libgambit.o
> In file included from gambit/lib\libgambit.cpp:574:
> ../../library/include/gambit/rational.h:119: error: 'lexical_cast' is not a template function
> In file included from gambit/lib\libgambit.cpp:575:
> ../../library/include/gambit/number.h: In constructor 'Gambit::Number::Number(const std::string&)':
> ../../library/include/gambit/number.h:39: error: 'lexical_cast' was not declared in this scope
> ../../library/include/gambit/number.h:39: error: expected primary-expression before '>' token
> ../../library/include/gambit/number.h: In member function 'Gambit::Number& Gambit::Number::operator=(const std::string&)':
> ../../library/include/gambit/number.h:47: error: 'lexical_cast' was not declared in this scope
> ../../library/include/gambit/number.h:47: error: expected primary-expression before '>' token
> In file included from gambit/lib\libgambit.cpp:580:
> ../../library/include/gambit/array.h: In member function 'int Gambit::Array<T>::InsertAt(const T&, int)':
> ../../library/include/gambit/array.h:37: error: there are no arguments to 'IndexException' that depend on a template parameter, so a declaration of 'IndexException' must be available
> ../../library/include/gambit/array.h:37: error: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
> ../../library/include/gambit/array.h: In constructor 'Gambit::Array<T>::Array(int, int)':
> ../../library/include/gambit/array.h:92: error: there are no arguments to 'RangeException' that depend on a template parameter, so a declaration of 'RangeException' must be available
> ../../library/include/gambit/array.h: In member function 'const T& Gambit::Array<T>::operator[](int) const':
> ../../library/include/gambit/array.h:164: error: there are no arguments to 'IndexException' that depend on a template parameter, so a declaration of 'IndexException' must be available
> ../../library/include/gambit/array.h: In member function 'T& Gambit::Array<T>::operator[](int)':
> ../../library/include/gambit/array.h:171: error: there are no arguments to 'IndexException' that depend on a template parameter, so a declaration of 'IndexException' must be available
> ../../library/include/gambit/array.h: In member function 'T Gambit::Array<T>::Remove(int)':
> ../../library/include/gambit/array.h:215: error: there are no arguments to 'IndexException' that depend on a template parameter, so a declaration of 'IndexException' must be available
> In file included from gambit/lib\libgambit.cpp:581:
> ../../library/include/gambit/list.h: In member function 'int Gambit::List<T>::InsertAt(const T&, int)':
> ../../library/include/gambit/list.h:202: error: there are no arguments to 'IndexException' that depend on a template parameter, so a declaration of 'IndexException' must be available
> ../../library/include/gambit/list.h: In member function 'const T& Gambit::List<T>::operator[](int) const':
> ../../library/include/gambit/list.h:289: error: there are no arguments to 'IndexException' that depend on a template parameter, so a declaration of 'IndexException' must be available
> ../../library/include/gambit/list.h: In member function 'T& Gambit::List<T>::operator[](int)':
> ../../library/include/gambit/list.h:302: error: there are no arguments to 'IndexException' that depend on a template parameter, so a declaration of 'IndexException' must be available
> ../../library/include/gambit/list.h: In member function 'virtual T Gambit::List<T>::Remove(int)':
> ../../library/include/gambit/list.h:348: error: there are no arguments to 'IndexException' that depend on a template parameter, so a declaration of 'IndexException' must be available
> In file included from gambit/lib\libgambit.cpp:582:
> ../../library/include/gambit/game.h: At global scope:
> ../../library/include/gambit/game.h:77: error: expected class-name before '{' token
> ../../library/include/gambit/game.h: In member function 'T* Gambit::GameObjectPtr<T>::operator->() const':
> ../../library/include/gambit/game.h:110: error: there are no arguments to 'NullException' that depend on a template parameter, so a declaration of 'NullException' must be available
> ../../library/include/gambit/game.h: At global scope:
> ../../library/include/gambit/game.h:170: error: expected class-name before '{' token
> ../../library/include/gambit/game.h: In constructor 'Gambit::UndefinedException::UndefinedException()':
> ../../library/include/gambit/game.h:172: error: class 'Gambit::UndefinedException' does not have any field named 'Exception'
> ../../library/include/gambit/game.h: In constructor 'Gambit::UndefinedException::UndefinedException(const std::string&)':
> ../../library/include/gambit/game.h:173: error: class 'Gambit::UndefinedException' does not have any field named 'Exception'
> ../../library/include/gambit/game.h: At global scope:
> ../../library/include/gambit/game.h:178: error: expected class-name before '{' token
> ../../library/include/gambit/game.h:186: error: expected class-name before '{' token
> ../../library/include/gambit/game.h: In constructor 'Gambit::InvalidFileException::InvalidFileException()':
> ../../library/include/gambit/game.h:188: error: class 'Gambit::InvalidFileException' does not have any field named 'Exception'
> ../../library/include/gambit/game.h: In constructor 'Gambit::InvalidFileException::InvalidFileException(const std::string&)':
> ../../library/include/gambit/game.h:189: error: class 'Gambit::InvalidFileException' does not have any field named 'Exception'
> ../../library/include/gambit/game.h: In member function 'T Gambit::PureBehaviorProfile::GetPayoff(int) const [with T = std::string]':
> ../../library/include/gambit/game.h:837: error: 'lexical_cast' was not declared in this scope
> ../../library/include/gambit/game.h:837: error: expected primary-expression before '>' token
> In file included from gambit/lib\libgambit.cpp:583:
> ../../library/include/gambit/mixed.h: At global scope:
> ../../library/include/gambit/mixed.h:35: error: field 'm_support' has incomplete type
> ../../library/include/gambit/mixed.h: In member function 'const T& Gambit::MixedStrategyProfileRep<T>::operator[](const Gambit::GameStrategy&) const':
> ../../library/include/gambit/mixed.h:47: error: 'm_support' was not declared in this scope
> ../../library/include/gambit/mixed.h: In member function 'T& Gambit::MixedStrategyProfileRep<T>::operator[](const Gambit::GameStrategy&)':
> ../../library/include/gambit/mixed.h:50: error: 'm_support' was not declared in this scope
> In file included from gambit/lib\libgambit.cpp:584:
> ../../library/include/gambit/behav.h: At global scope:
> ../../library/include/gambit/behav.h:36: error: 'BehaviorSupportProfile' does not name a type
> ../../library/include/gambit/behav.h:80: error: expected ',' or '...' before '&' token
> ../../library/include/gambit/behav.h:80: error: ISO C++ forbids declaration of 'BehaviorSupportProfile' with no type
> ../../library/include/gambit/behav.h:162: error: ISO C++ forbids declaration of 'BehaviorSupportProfile' with no type
> ../../library/include/gambit/behav.h:162: error: expected ';' before '&' token
> ../../library/include/gambit/behav.h:164: error: expected `;' before 'bool'
> ../../library/include/gambit/behav.h: In member function 'const T& Gambit::MixedBehaviorProfile<T>::operator[](const Gambit::GameAction&) const':
> ../../library/include/gambit/behav.h:107: error: 'm_support' was not declared in this scope
> ../../library/include/gambit/behav.h: In member function 'T& Gambit::MixedBehaviorProfile<T>::operator[](const Gambit::GameAction&)':
> ../../library/include/gambit/behav.h:111: error: 'm_support' was not declared in this scope
> ../../library/include/gambit/behav.h: In member function 'const T& Gambit::MixedBehaviorProfile<T>::operator()(const Gambit::GameAction&) const':
> ../../library/include/gambit/behav.h:116: error: 'm_support' was not declared in this scope
> ../../library/include/gambit/behav.h: In member function 'T& Gambit::MixedBehaviorProfile<T>::operator()(const Gambit::GameAction&)':
> ../../library/include/gambit/behav.h:120: error: 'm_support' was not declared in this scope
> ../../library/include/gambit/behav.h: In member function 'Gambit::Game Gambit::MixedBehaviorProfile<T>::GetGame() const':
> ../../library/include/gambit/behav.h:161: error: 'm_support' was not declared in this scope
> In file included from ../../library/include/gambit/gambit.h:139,
>                  from ../../library/include/gambit/stratspt.h:26,
>                  from gambit/lib\libgambit.cpp:585:
> ../../library/include/gambit/stratitr.h: At global scope:
> ../../library/include/gambit/stratitr.h:40: error: field 'm_support' has incomplete type
> In file included from ../../library/include/gambit/gtracer/gtracer.h:28,
>                  from ../../library/include/gambit/nash/gnm.h:27,
>                  from gambit/lib\libgambit.cpp:593:
> ../../library/include/gambit/gtracer/cmatrix.h: In member function 'bool Gambit::gametracer::cvector::operator==(const Gambit::gametracer::cvector&) const':
> ../../library/include/gambit/gtracer/cmatrix.h:212: error: 'bcmp' was not declared in this scope
> ../../library/include/gambit/gtracer/cmatrix.h: In member function 'bool Gambit::gametracer::cvector::IsEqual(Gambit::gametracer::cvector*) const':
> ../../library/include/gambit/gtracer/cmatrix.h:221: error: 'bcmp' was not declared in this scope
> ../../library/include/gambit/gtracer/cmatrix.h: In member function 'bool Gambit::gametracer::cvector::operator!=(const Gambit::gametracer::cvector&) const':
> ../../library/include/gambit/gtracer/cmatrix.h:234: error: 'bcmp' was not declared in this scope
> ../../library/include/gambit/gtracer/cmatrix.h: In member function 'bool Gambit::gametracer::cmatrix::operator==(const Gambit::gametracer::cmatrix&) const':
> ../../library/include/gambit/gtracer/cmatrix.h:741: error: 'bcmp' was not declared in this scope
> ../../library/include/gambit/gtracer/cmatrix.h: In member function 'bool Gambit::gametracer::cmatrix::operator!=(const Gambit::gametracer::cmatrix&) const':
> ../../library/include/gambit/gtracer/cmatrix.h:754: error: 'bcmp' was not declared in this scope
> In file included from ../../library/include/gambit/gtracer/nfgame.h:28,
>                  from ../../library/include/gambit/gtracer/gtracer.h:29,
>                  from ../../library/include/gambit/nash/gnm.h:27,
>                  from gambit/lib\libgambit.cpp:593:
> ../../library/include/gambit/gtracer/gnmgame.h: In member function 'void Gambit::gametracer::gnmgame::randomFullStrategy(Gambit::gametracer::cvector&, int)':
> ../../library/include/gambit/gtracer/gnmgame.h:194: error: 'drand48' was not declared in this scope
> ../../library/include/gambit/gtracer/gnmgame.h: In member function 'long long unsigned int Gambit::gametracer::gnmgame::randomSupportStrategy(Gambit::gametracer::cvector&, int, double)':
> ../../library/include/gambit/gtracer/gnmgame.h:220: error: 'drand48' was not declared in this scope
> ../../library/include/gambit/array.h: In member function 'T& Gambit::Array<T>::operator[](int) [with T = Gambit::Number]':
> ../../library/include/gambit/game.h:241:   instantiated from here
> ../../library/include/gambit/array.h:171: error: expected primary-expression
> ../../library/include/gambit/array.h: In member function 'const T& Gambit::Array<T>::operator[](int) const [with T = Gambit::GameObjectPtr<Gambit::GameStrategyRep>]':
> ../../library/include/gambit/game.h:544:   instantiated from here
> ../../library/include/gambit/array.h:164: error: expected primary-expression
> ../../library/include/gambit/game.h: In member function 'T* Gambit::GameObjectPtr<T>::operator->() const [with T = Gambit::GamePlayerRep]':
> ../../library/include/gambit/game.h:547:   instantiated from here
> ../../library/include/gambit/game.h:110: error: expected primary-expression
> ../../library/include/gambit/array.h: In member function 'const T& Gambit::Array<T>::operator[](int) const [with T = Gambit::GameStrategyRep*]':
> ../../library/include/gambit/game.h:826:   instantiated from here
> ../../library/include/gambit/array.h:164: error: expected primary-expression
> ../../library/include/gambit/game.h: In member function 'T* Gambit::GameObjectPtr<T>::operator->() const [with T = Gambit::GameRep]':
> ../../library/include/gambit/game.h:831:   instantiated from here
> ../../library/include/gambit/game.h:110: error: expected primary-expression
> ../../library/include/gambit/array.h: In member function 'const T& Gambit::Array<T>::operator[](int) const [with T = Gambit::GamePlayerRep*]':
> ../../library/include/gambit/gameagg.h:88:   instantiated from here
> ../../library/include/gambit/array.h:164: error: expected primary-expression
> ../../library/include/gambit/game.h: In member function 'T* Gambit::GameObjectPtr<T>::operator->() const [with T = Gambit::GameInfosetRep]':
> ../../library/include/gambit/behavspt.h:77:   instantiated from here
> ../../library/include/gambit/game.h:110: error: expected primary-expression
> ../../library/include/gambit/array.h: In member function 'const T& Gambit::Array<T>::operator[](int) const [with T = Gambit::Array<Gambit::Array<Gambit::GameObjectPtr<Gambit::GameActionRep> > >]':
> ../../library/include/gambit/behavspt.h:77:   instantiated from here
> ../../library/include/gambit/array.h:164: error: expected primary-expression
> ../../library/include/gambit/array.h: In member function 'const T& Gambit::Array<T>::operator[](int) const [with T = Gambit::Array<Gambit::GameObjectPtr<Gambit::GameActionRep> >]':
> ../../library/include/gambit/behavspt.h:77:   instantiated from here
> ../../library/include/gambit/array.h:164: error: expected primary-expression
> ../../library/include/gambit/array.h: In member function 'const T& Gambit::Array<T>::operator[](int) const [with T = Gambit::GameObjectPtr<Gambit::GameActionRep>]':
> ../../library/include/gambit/behavspt.h:86:   instantiated from here
> ../../library/include/gambit/array.h:164: error: expected primary-expression
> ../../library/include/gambit/array.h: In member function 'const T& Gambit::Array<T>::operator[](int) const [with T = Gambit::Array<Gambit::GameObjectPtr<Gambit::GameStrategyRep> >]':
> ../../library/include/gambit/stratspt.h:81:   instantiated from here
> ../../library/include/gambit/array.h:164: error: expected primary-expression
> ../../library/include/gambit/game.h: In member function 'T* Gambit::GameObjectPtr<T>::operator->() const [with T = Gambit::GameStrategyRep]':
> ../../library/include/gambit/stratspt.h:103:   instantiated from here
> ../../library/include/gambit/game.h:110: error: expected primary-expression
> ../../library/include/gambit/array.h: In member function 'const T& Gambit::Array<T>::operator[](int) const [with T = int]':
> ../../library/include/gambit/stratspt.h:107:   instantiated from here
> ../../library/include/gambit/array.h:164: error: expected primary-expression
> ../../library/include/gambit/mixed.h: In member function 'Gambit::Game Gambit::MixedStrategyProfile<T>::GetGame() const [with T = double]':
> ../tools/logit/nfglogit.h:42:   instantiated from here
> ../../library/include/gambit/mixed.h:202: error: 'class Gambit::MixedStrategyProfileRep<double>' has no member named 'm_support'
> ../../library/include/gambit/gambit.h: In function 'D Gambit::lexical_cast(const S&) [with D = Gambit::Rational, S = std::string]':
> gambit/lib\util.h:87:   instantiated from here
> ../../library/include/gambit/gambit.h:38: error: conversion from 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >' to non-scalar type 'Gambit::Rational' requested
> ../../library/include/gambit/game.h: In member function 'T* Gambit::GameObjectPtr<T>::operator->() const [with T = Gambit::GameActionRep]':
> gambit/lib\libgambit.cpp:4813:   instantiated from here
> ../../library/include/gambit/game.h:110: error: expected primary-expression
> ../../library/include/gambit/game.h: In member function 'T* Gambit::GameObjectPtr<T>::operator->() const [with T = Gambit::GameOutcomeRep]':
> gambit/lib\libgambit.cpp:13469:   instantiated from here
> ../../library/include/gambit/game.h:110: error: expected primary-expression
> ../../library/include/gambit/game.h: In member function 'T* Gambit::GameObjectPtr<T>::operator->() const [with T = Gambit::GameNodeRep]':
> gambit/lib\libgambit.cpp:16438:   instantiated from here
> ../../library/include/gambit/game.h:110: error: expected primary-expression
> ../../library/include/gambit/array.h: In member function 'T& Gambit::Array<T>::operator[](int) [with T = int]':
> gambit/lib\libgambit.cpp:21808:   instantiated from here
> ../../library/include/gambit/array.h:171: error: expected primary-expression
> ../../library/include/gambit/mixed.h: In member function 'const Gambit::StrategySupportProfile& Gambit::MixedStrategyProfile<T>::GetSupport() const [with T = double]':
> gambit/lib\libgambit.cpp:34608:   instantiated from here
> ../../library/include/gambit/mixed.h:204: error: 'class Gambit::MixedStrategyProfileRep<double>' has no member named 'm_support'
> ../../library/include/gambit/mixed.h: In member function 'const Gambit::StrategySupportProfile& Gambit::MixedStrategyProfile<T>::GetSupport() const [with T = Gambit::Rational]':
> gambit/lib\libgambit.cpp:36219:   instantiated from here
> ../../library/include/gambit/mixed.h:204: error: 'class Gambit::MixedStrategyProfileRep<Gambit::Rational>' has no member named 'm_support'
> ../../library/include/gambit/mixed.h: In member function 'Gambit::Game Gambit::MixedStrategyProfile<T>::GetGame() const [with T = Gambit::Rational]':
> gambit/lib\libgambit.cpp:38023:   instantiated from here
> ../../library/include/gambit/mixed.h:202: error: 'class Gambit::MixedStrategyProfileRep<Gambit::Rational>' has no member named 'm_support'
> ../../library/include/gambit/list.h: In member function 'int Gambit::List<T>::InsertAt(const T&, int) [with T = Gambit::MixedStrategyProfile<Gambit::Rational>]':
> ../../library/include/gambit/list.h:338:   instantiated from 'int Gambit::List<T>::Append(const T&) [with T = Gambit::MixedStrategyProfile<Gambit::Rational>]'
> ../../library/include/gambit/nash/enumpure.h:55:   instantiated from here
> ../../library/include/gambit/list.h:202: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'int Gambit::List<T>::InsertAt(const T&, int) [with T = Gambit::MixedBehaviorProfile<Gambit::Rational>]':
> ../../library/include/gambit/list.h:338:   instantiated from 'int Gambit::List<T>::Append(const T&) [with T = Gambit::MixedBehaviorProfile<Gambit::Rational>]'
> ../../library/include/gambit/nash/enumpure.h:85:   instantiated from here
> ../../library/include/gambit/list.h:202: error: expected primary-expression
> ../../library/include/gambit/array.h: In member function 'T& Gambit::Array<T>::operator[](int) [with T = double]':
> ../../library/include/gambit/mixed.h:181:   instantiated from 'const T& Gambit::MixedStrategyProfile<T>::operator[](int) const [with T = double]'
> ../tools/logit/nfglogit.h:44:   instantiated from here
> ../../library/include/gambit/array.h:171: error: expected primary-expression
> ../../library/include/gambit/array.h: In member function 'const T& Gambit::Array<T>::operator[](int) const [with T = Gambit::Number]':
> ../../library/include/gambit/game.h:237:   instantiated from 'const T& Gambit::GameOutcomeRep::GetPayoff(int) const [with T = Gambit::Number]'
> gambit/lib\libgambit.cpp:14492:   instantiated from here
> ../../library/include/gambit/array.h:164: error: expected primary-expression
> ../../library/include/gambit/array.h: In member function 'T& Gambit::Array<T>::operator[](int) [with T = Gambit::Rational]':
> ../../library/include/gambit/mixed.h:183:   instantiated from 'T& Gambit::MixedStrategyProfile<T>::operator[](int) [with T = Gambit::Rational]'
> gambit/lib\libgambit.cpp:36297:   instantiated from here
> ../../library/include/gambit/array.h:171: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'const T& Gambit::List<T>::operator[](int) const [with T = Gambit::MixedStrategyProfile<Gambit::Rational>]':
> gambit/lib\util.h:78:   instantiated from 'T* copyitem(const C<T>&, const X&) [with C = Gambit::List, T = Gambit::MixedStrategyProfile<Gambit::Rational>, X = int]'
> gambit/lib\libgambit.cpp:57912:   instantiated from here
> ../../library/include/gambit/list.h:289: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'const T& Gambit::List<T>::operator[](int) const [with T = Gambit::MixedBehaviorProfile<Gambit::Rational>]':
> gambit/lib\util.h:78:   instantiated from 'T* copyitem(const C<T>&, const X&) [with C = Gambit::List, T = Gambit::MixedBehaviorProfile<Gambit::Rational>, X = int]'
> gambit/lib\libgambit.cpp:58376:   instantiated from here
> ../../library/include/gambit/list.h:289: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'const T& Gambit::List<T>::operator[](int) const [with T = Gambit::MixedStrategyProfile<double>]':
> gambit/lib\util.h:78:   instantiated from 'T* copyitem(const C<T>&, const X&) [with C = Gambit::List, T = Gambit::MixedStrategyProfile<double>, X = int]'
> gambit/lib\libgambit.cpp:58787:   instantiated from here
> ../../library/include/gambit/list.h:289: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'const T& Gambit::List<T>::operator[](int) const [with T = Gambit::MixedBehaviorProfile<double>]':
> gambit/lib\util.h:78:   instantiated from 'T* copyitem(const C<T>&, const X&) [with C = Gambit::List, T = Gambit::MixedBehaviorProfile<double>, X = int]'
> gambit/lib\libgambit.cpp:60082:   instantiated from here
> ../../library/include/gambit/list.h:289: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'const T& Gambit::List<T>::operator[](int) const [with T = Gambit::LogitQREMixedStrategyProfile]':
> gambit/lib\util.h:78:   instantiated from 'T* copyitem(const C<T>&, const X&) [with C = Gambit::List, T = Gambit::LogitQREMixedStrategyProfile, X = int]'
> gambit/lib\libgambit.cpp:65657:   instantiated from here
> ../../library/include/gambit/list.h:289: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'T Gambit::List<T>::Remove(int) [with T = Gambit::Vector<Gambit::Rational>]':
> gambit/lib\libgambit.cpp:84516:   instantiated from here
> ../../library/include/gambit/list.h:348: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'T Gambit::List<T>::Remove(int) [with T = Gambit::Vector<double>]':
> gambit/lib\libgambit.cpp:84516:   instantiated from here
> ../../library/include/gambit/list.h:348: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'T Gambit::List<T>::Remove(int) [with T = Gambit::List<bool>]':
> gambit/lib\libgambit.cpp:84516:   instantiated from here
> ../../library/include/gambit/list.h:348: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'T Gambit::List<T>::Remove(int) [with T = bool]':
> gambit/lib\libgambit.cpp:84516:   instantiated from here
> ../../library/include/gambit/list.h:348: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'T Gambit::List<T>::Remove(int) [with T = Gambit::MixedBehaviorProfile<double>]':
> gambit/lib\libgambit.cpp:84516:   instantiated from here
> ../../library/include/gambit/list.h:348: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'T Gambit::List<T>::Remove(int) [with T = Gambit::MixedStrategyProfile<double>]':
> gambit/lib\libgambit.cpp:84516:   instantiated from here
> ../../library/include/gambit/list.h:348: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'T Gambit::List<T>::Remove(int) [with T = Gambit::LogitQREMixedStrategyProfile]':
> gambit/lib\libgambit.cpp:84516:   instantiated from here
> ../../library/include/gambit/list.h:348: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'T Gambit::List<T>::Remove(int) [with T = Gambit::MixedBehaviorProfile<Gambit::Rational>]':
> gambit/lib\libgambit.cpp:84516:   instantiated from here
> ../../library/include/gambit/list.h:348: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'T Gambit::List<T>::Remove(int) [with T = Gambit::MixedStrategyProfile<Gambit::Rational>]':
> gambit/lib\libgambit.cpp:84516:   instantiated from here
> ../../library/include/gambit/list.h:348: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'T Gambit::List<T>::Remove(int) [with T = Gambit::Array<int>]':
> gambit/lib\libgambit.cpp:84516:   instantiated from here
> ../../library/include/gambit/list.h:348: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'T Gambit::List<T>::Remove(int) [with T = int]':
> gambit/lib\libgambit.cpp:84516:   instantiated from here
> ../../library/include/gambit/list.h:348: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'int Gambit::List<T>::InsertAt(const T&, int) [with T = Gambit::Vector<Gambit::Rational>]':
> ../../library/include/gambit/list.h:338:   instantiated from 'int Gambit::List<T>::Append(const T&) [with T = Gambit::Vector<Gambit::Rational>]'
> gambit/lib\libgambit.cpp:84516:   instantiated from here
> ../../library/include/gambit/list.h:202: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'int Gambit::List<T>::InsertAt(const T&, int) [with T = Gambit::Vector<double>]':
> ../../library/include/gambit/list.h:338:   instantiated from 'int Gambit::List<T>::Append(const T&) [with T = Gambit::Vector<double>]'
> gambit/lib\libgambit.cpp:84516:   instantiated from here
> ../../library/include/gambit/list.h:202: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'int Gambit::List<T>::InsertAt(const T&, int) [with T = Gambit::List<bool>]':
> ../../library/include/gambit/list.h:338:   instantiated from 'int Gambit::List<T>::Append(const T&) [with T = Gambit::List<bool>]'
> gambit/lib\libgambit.cpp:84516:   instantiated from here
> ../../library/include/gambit/list.h:202: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'int Gambit::List<T>::InsertAt(const T&, int) [with T = bool]':
> ../../library/include/gambit/list.h:338:   instantiated from 'int Gambit::List<T>::Append(const T&) [with T = bool]'
> gambit/lib\libgambit.cpp:84516:   instantiated from here
> ../../library/include/gambit/list.h:202: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'int Gambit::List<T>::InsertAt(const T&, int) [with T = Gambit::MixedBehaviorProfile<double>]':
> ../../library/include/gambit/list.h:338:   instantiated from 'int Gambit::List<T>::Append(const T&) [with T = Gambit::MixedBehaviorProfile<double>]'
> gambit/lib\libgambit.cpp:84516:   instantiated from here
> ../../library/include/gambit/list.h:202: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'int Gambit::List<T>::InsertAt(const T&, int) [with T = Gambit::MixedStrategyProfile<double>]':
> ../../library/include/gambit/list.h:338:   instantiated from 'int Gambit::List<T>::Append(const T&) [with T = Gambit::MixedStrategyProfile<double>]'
> gambit/lib\libgambit.cpp:84516:   instantiated from here
> ../../library/include/gambit/list.h:202: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'int Gambit::List<T>::InsertAt(const T&, int) [with T = Gambit::LogitQREMixedStrategyProfile]':
> ../../library/include/gambit/list.h:338:   instantiated from 'int Gambit::List<T>::Append(const T&) [with T = Gambit::LogitQREMixedStrategyProfile]'
> gambit/lib\libgambit.cpp:84516:   instantiated from here
> ../../library/include/gambit/list.h:202: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'int Gambit::List<T>::InsertAt(const T&, int) [with T = Gambit::Array<int>]':
> ../../library/include/gambit/list.h:338:   instantiated from 'int Gambit::List<T>::Append(const T&) [with T = Gambit::Array<int>]'
> gambit/lib\libgambit.cpp:84516:   instantiated from here
> ../../library/include/gambit/list.h:202: error: expected primary-expression
> ../../library/include/gambit/list.h: In member function 'int Gambit::List<T>::InsertAt(const T&, int) [with T = int]':
> ../../library/include/gambit/list.h:338:   instantiated from 'int Gambit::List<T>::Append(const T&) [with T = int]'
> gambit/lib\libgambit.cpp:84516:   instantiated from here
> ../../library/include/gambit/list.h:202: error: expected primary-expression
> error: command 'gcc' failed with exit status 1

**Comment by tturocy** [comment]
That is correct.  The Python bindings aren't supported on Windows.
