### ISSUE TITLE
'module' object has no attribute 'read_game'

### ISSUE THREAD

**Issue by Sud26** [gambitproject/gambit#233]
This error pops when ever I load a .nfg file using the ipython command " g = gambit.read_game( "2 person game.nfg" ) Plz reply asap. Thank you

**Comment by tturocy** [comment]
Then you don't have the Gambit module installed properly.

**Comment by Sud26** [comment]
It shows version 15.1.0

**Comment by tturocy** [comment]
Are you by any chance running this from within the build directory?

**Comment by Sud26** [comment]
Yes I'm.

**Comment by tturocy** [comment]
Yeah, you should never import and run a python module from its build directory.

Closing.

As a tip: "Plz reply asap" is *MASSIVELY RUDE*. Ordinarily I would have closed this straightaway and not responded.  Fortunately I am in a good mood today so I have made an exception.

**Comment by Sud26** [comment]
I'm extremely sorry Sir for my comment. Thank you for your valuable time. I really appreciate your work with Gambit.  I'm currently developing a six player simultaneous game (24 actions throughout the game) for Gambit with Ipython notebook.

Regarding the error even though I don't  run it from its build directory I get the same error.

**Comment by sruju333** [comment]
> I'm extremely sorry Sir for my comment. Thank you for your valuable time. I really appreciate your work with Gambit. I'm currently developing a six player simultaneous game (24 actions throughout the game) for Gambit with Ipython notebook.
> 
> Regarding the error even though I don't run it from its build directory I get the same error.

I personally think that you need not apologise for asking. The other participant could have informed the guidelines in a nicer way!

**Comment by userbunny-rgb** [comment]
looks like they have a lot of errors in their documentation

**Comment by userbunny-rgb** [comment]
> I'm extremely sorry Sir for my comment. Thank you for your valuable time. I really appreciate your work with Gambit. I'm currently developing a six player simultaneous game (24 actions throughout the game) for Gambit with Ipython notebook.
> 
> Regarding the error even though I don't run it from its build directory I get the same error.

hey don't apologise, they have a lot of bugs in their own software. so it obviously won't run properly... unless they are actually willing to share some real solution!
