### ISSUE TITLE
How to interpret Nash profile (I know I'm asking a stupid question)

### ISSUE THREAD

**Issue by Sud26** [gambitproject/gambit#234]
I'm extremely apologize for my comment last time Sir. Can you help me out with the nash profile for pure and mixed strategy? I'm sorry for taking too much of your time.

 import gambit

In [3]: g = gambit.Game.new_table ([2,2])

In [4]: g.players[0].label = "government"

In [5]: g.players[1].label = "terrorist"

In [6]: g.players[0].strategies[0].label = "CT-ops"

In [7]: g.players[0].strategies[1].label = "peace"

In [8]: g.players[1].strategies[0].label = "terror attack"

In [9]: g.players[1].strategies[1].label = "peace"

In [10]: g[0,0] [0] =-5

In [11]: g[0,0] [1] =-5

In [12]: g[0,1] [0] =3

In [13]: g[0,1] [1] =-10

In [14]: g[1,0] [0] =-8

In [15]: g[1,0] [1] =6

In [16]: g[1,1] [0] =0

In [17]: g[1,1] [1] =0

In [22]: Solver = gambit.nash.ExternalEnumMixedSolver()

In [24]: Solver.solve(g)
Out[24]: [<NashProfile for '': [[1.0, 0.0], [1.0, 0.0]]>]

In [35]: Solver = gambit.nash.ExternalEnumPureSolver()

In [36]: Solver.solve(g)
Out[36]: [<NashProfile for '': [[Fraction(1, 1), Fraction(0, 1)], [Fraction(1, 1), Fraction(0, 1)]]>]

**Comment by stengel** [comment]
Hi, you might also try
http://cgi.csc.liv.ac.uk/~rahul/bimatrix_solver/

* Sud26 <notifications@github.com> [07-03-2018 21:33:06 +0000]:

> I'm extremely apologize for my comment last time Sir. Can you help me out with the nash profile for pure and mixed strategy? I'm sorry for taking too much of your time.
> 
>  import gambit
> 
> In [3]: g = gambit.Game.new_table ([2,2])
> 
> In [4]: g.players[0].label = "government"
> 
> In [5]: g.players[1].label = "terrorist"
> 
> In [6]: g.players[0].strategies[0].label = "CT-ops"
> 
> In [7]: g.players[0].strategies[1].label = "peace"
> 
> In [8]: g.players[1].strategies[0].label = "terror attack"
> 
> In [9]: g.players[1].strategies[1].label = "peace"
> 
> In [10]: g[0,0] [0] =-5
> 
> In [11]: g[0,0] [1] =-5
> 
> In [12]: g[0,1] [0] =3
> 
> In [13]: g[0,1] [1] =-10
> 
> In [14]: g[1,0] [0] =-8
> 
> In [15]: g[1,0] [1] =6
> 
> In [16]: g[1,1] [0] =0
> 
> In [17]: g[1,1] [1] =0
> 
> In [22]: Solver = gambit.nash.ExternalEnumMixedSolver()
> 
> In [24]: Solver.solve(g)
> Out[24]: [<NashProfile for '': [[1.0, 0.0], [1.0, 0.0]]>]
> 
> In [35]: Solver = gambit.nash.ExternalEnumPureSolver()
> 
> In [36]: Solver.solve(g)
> Out[36]: [<NashProfile for '': [[Fraction(1, 1), Fraction(0, 1)], [Fraction(1, 1), Fraction(0, 1)]]>]
> 
> 
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/gambitproject/gambit/issues/234

-- 
Prof Bernhard von Stengel         email: stengel@nash.lse.ac.uk
Department of Mathematics         http://www.maths.lse.ac.uk/Personal/stengel
London School of Economics        phone: +44-20-7955 6438  (office)
Houghton St, Room COL 4.12               +44-20-7226 2325  (home)
London WC2A 2AE, United Kingdom

**Comment by tturocy** [comment]
http://gambitproject.readthedocs.io/en/latest/pyapi.html#mixed-strategy-and-behavior-profiles
