### ISSUE TITLE
Problem while building Gambit 16.0.1 from source

### ISSUE THREAD

**Issue by Sud26** [gambitproject/gambit#236]
The './configure' command went through, however I'm having trouble with 'make'. The gcc version is 7.2.0. 

make  all-recursive
make[1]: Entering directory '/home/sudhan/gambit-16.0.1'
Making all in contrib
make[2]: Entering directory '/home/sudhan/gambit-16.0.1/contrib'
Making all in scripts
make[3]: Entering directory '/home/sudhan/gambit-16.0.1/contrib/scripts'
Making all in enumpoly
make[4]: Entering directory '/home/sudhan/gambit-16.0.1/contrib/scripts/enumpoly'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/sudhan/gambit-16.0.1/contrib/scripts/enumpoly'
make[4]: Entering directory '/home/sudhan/gambit-16.0.1/contrib/scripts'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/sudhan/gambit-16.0.1/contrib/scripts'
make[3]: Leaving directory '/home/sudhan/gambit-16.0.1/contrib/scripts'
make[3]: Entering directory '/home/sudhan/gambit-16.0.1/contrib'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/sudhan/gambit-16.0.1/contrib'
make[2]: Leaving directory '/home/sudhan/gambit-16.0.1/contrib'
make[2]: Entering directory '/home/sudhan/gambit-16.0.1'
depbase=`echo library/src/integer.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I.  -I./src -I./library/include -I./src/labenski/include    -g -O2 -MT library/src/integer.o -MD -MP -MF $depbase.Tpo -c -o library/src/integer.o library/src/integer.cc &&\
mv -f $depbase.Tpo $depbase.Po
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h: In member function ‘void Gambit::weak_ptr<T>::swap(const Gambit::weak_ptr<T>&)’:
./library/include/gambit/shared_ptr.h:137:37: error: no matching function for call to ‘swap(long int*&, long int* const&)’
     std::swap(m_count, other.m_count);
                                     ^
In file included from /usr/include/c++/7/bits/nested_exception.h:40:0,
                 from /usr/include/c++/7/exception:143,
                 from /usr/include/c++/7/ios:39,
                 from /usr/include/c++/7/ostream:38,
                 from /usr/include/c++/7/iostream:39,
                 from library/src/integer.cc:37:
/usr/include/c++/7/bits/move.h:187:5: note: candidate: template<class _Tp> typename std::enable_if<std::__and_<std::__not_<std::__is_tuple_like<_Tp> >, std::is_move_constructible<_Tp>, std::is_move_assignable<_Tp> >::value>::type std::swap(_Tp&, _Tp&)
     swap(_Tp& __a, _Tp& __b)
     ^~~~
/usr/include/c++/7/bits/move.h:187:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   deduced conflicting types for parameter ‘_Tp’ (‘long int*’ and ‘long int* const’)
     std::swap(m_count, other.m_count);
                                     ^
In file included from /usr/include/c++/7/bits/nested_exception.h:40:0,
                 from /usr/include/c++/7/exception:143,
                 from /usr/include/c++/7/ios:39,
                 from /usr/include/c++/7/ostream:38,
                 from /usr/include/c++/7/iostream:39,
                 from library/src/integer.cc:37:
/usr/include/c++/7/bits/move.h:210:5: note: candidate: template<class _Tp, long unsigned int _Nm> typename std::enable_if<std::__is_swappable<_Tp>::value>::type std::swap(_Tp (&)[_Nm], _Tp (&)[_Nm])
     swap(_Tp (&__a)[_Nm], _Tp (&__b)[_Nm])
     ^~~~
/usr/include/c++/7/bits/move.h:210:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types ‘_Tp [_Nm]’ and ‘long int*’
     std::swap(m_count, other.m_count);
                                     ^
In file included from /usr/include/c++/7/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/7/bits/char_traits.h:39,
                 from /usr/include/c++/7/ios:40,
                 from /usr/include/c++/7/ostream:38,
                 from /usr/include/c++/7/iostream:39,
                 from library/src/integer.cc:37:
/usr/include/c++/7/bits/stl_pair.h:490:5: note: candidate: template<class _T1, class _T2> typename std::enable_if<std::__and_<std::__is_swappable<_T1>, std::__is_swappable<_T2> >::value>::type std::swap(std::pair<_T1, _T2>&, std::pair<_T1, _T2>&)
     swap(pair<_T1, _T2>& __x, pair<_T1, _T2>& __y)
     ^~~~
/usr/include/c++/7/bits/stl_pair.h:490:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types ‘std::pair<_T1, _T2>’ and ‘long int*’
     std::swap(m_count, other.m_count);
                                     ^
In file included from /usr/include/c++/7/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/7/bits/char_traits.h:39,
                 from /usr/include/c++/7/ios:40,
                 from /usr/include/c++/7/ostream:38,
                 from /usr/include/c++/7/iostream:39,
                 from library/src/integer.cc:37:
/usr/include/c++/7/bits/stl_pair.h:498:5: note: candidate: template<class _T1, class _T2> typename std::enable_if<(! std::__and_<std::__is_swappable<_T1>, std::__is_swappable<_T2> >::value)>::type std::swap(std::pair<_T1, _T2>&, std::pair<_T1, _T2>&) <deleted>
     swap(pair<_T1, _T2>&, pair<_T1, _T2>&) = delete;
     ^~~~
/usr/include/c++/7/bits/stl_pair.h:498:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types ‘std::pair<_T1, _T2>’ and ‘long int*’
     std::swap(m_count, other.m_count);
                                     ^
In file included from /usr/include/c++/7/string:52:0,
                 from /usr/include/c++/7/bits/locale_classes.h:40,
                 from /usr/include/c++/7/bits/ios_base.h:41,
                 from /usr/include/c++/7/ios:42,
                 from /usr/include/c++/7/ostream:38,
                 from /usr/include/c++/7/iostream:39,
                 from library/src/integer.cc:37:
/usr/include/c++/7/bits/basic_string.h:6234:5: note: candidate: template<class _CharT, class _Traits, class _Alloc> void std::swap(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&)
     swap(basic_string<_CharT, _Traits, _Alloc>& __lhs,
     ^~~~
/usr/include/c++/7/bits/basic_string.h:6234:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>’ and ‘long int*’
     std::swap(m_count, other.m_count);
                                     ^
In file included from /usr/include/c++/7/tuple:39:0,
                 from /usr/include/c++/7/bits/unique_ptr.h:37,
                 from /usr/include/c++/7/bits/locale_conv.h:41,
                 from /usr/include/c++/7/locale:43,
                 from /usr/include/c++/7/iomanip:43,
                 from ./library/include/gambit/gambit.h:29,
                 from library/src/integer.cc:45:
/usr/include/c++/7/array:294:5: note: candidate: template<class _Tp, long unsigned int _Nm> typename std::enable_if<typename std::__array_traits<_Tp, _Nm>::_Is_swappable:: value>::type std::swap(std::array<_Tp, _Nm>&, std::array<_Tp, _Nm>&)
     swap(array<_Tp, _Nm>& __one, array<_Tp, _Nm>& __two)
     ^~~~
/usr/include/c++/7/array:294:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types ‘std::array<_Tp, _Nm>’ and ‘long int*’
     std::swap(m_count, other.m_count);
                                     ^
In file included from /usr/include/c++/7/tuple:39:0,
                 from /usr/include/c++/7/bits/unique_ptr.h:37,
                 from /usr/include/c++/7/bits/locale_conv.h:41,
                 from /usr/include/c++/7/locale:43,
                 from /usr/include/c++/7/iomanip:43,
                 from ./library/include/gambit/gambit.h:29,
                 from library/src/integer.cc:45:
/usr/include/c++/7/array:302:5: note: candidate: template<class _Tp, long unsigned int _Nm> typename std::enable_if<(! typename std::__array_traits<_Tp, _Nm>::_Is_swappable:: value)>::type std::swap(std::array<_Tp, _Nm>&, std::array<_Tp, _Nm>&) <deleted>
     swap(array<_Tp, _Nm>&, array<_Tp, _Nm>&) = delete;
     ^~~~
/usr/include/c++/7/array:302:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types ‘std::array<_Tp, _Nm>’ and ‘long int*’
     std::swap(m_count, other.m_count);
                                     ^
In file included from /usr/include/c++/7/bits/unique_ptr.h:37:0,
                 from /usr/include/c++/7/bits/locale_conv.h:41,
                 from /usr/include/c++/7/locale:43,
                 from /usr/include/c++/7/iomanip:43,
                 from ./library/include/gambit/gambit.h:29,
                 from library/src/integer.cc:45:
/usr/include/c++/7/tuple:1602:5: note: candidate: template<class ... _Elements> typename std::enable_if<std::__and_<std::__is_swappable<_Elements>...>::value>::type std::swap(std::tuple<_Tps ...>&, std::tuple<_Tps ...>&)
     swap(tuple<_Elements...>& __x, tuple<_Elements...>& __y)
     ^~~~
/usr/include/c++/7/tuple:1602:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types ‘std::tuple<_Tps ...>’ and ‘long int*’
     std::swap(m_count, other.m_count);
                                     ^
In file included from /usr/include/c++/7/bits/unique_ptr.h:37:0,
                 from /usr/include/c++/7/bits/locale_conv.h:41,
                 from /usr/include/c++/7/locale:43,
                 from /usr/include/c++/7/iomanip:43,
                 from ./library/include/gambit/gambit.h:29,
                 from library/src/integer.cc:45:
/usr/include/c++/7/tuple:1609:5: note: candidate: template<class ... _Elements> typename std::enable_if<(! std::__and_<std::__is_swappable<_Elements>...>::value)>::type std::swap(std::tuple<_Tps ...>&, std::tuple<_Tps ...>&) <deleted>
     swap(tuple<_Elements...>&, tuple<_Elements...>&) = delete;
     ^~~~
/usr/include/c++/7/tuple:1609:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types ‘std::tuple<_Tps ...>’ and ‘long int*’
     std::swap(m_count, other.m_count);
                                     ^
In file included from /usr/include/c++/7/bits/locale_conv.h:41:0,
                 from /usr/include/c++/7/locale:43,
                 from /usr/include/c++/7/iomanip:43,
                 from ./library/include/gambit/gambit.h:29,
                 from library/src/integer.cc:45:
/usr/include/c++/7/bits/unique_ptr.h:669:5: note: candidate: template<class _Tp, class _Dp> typename std::enable_if<std::__is_swappable<_T2>::value>::type std::swap(std::unique_ptr<_Tp, _Dp>&, std::unique_ptr<_Tp, _Dp>&)
     swap(unique_ptr<_Tp, _Dp>& __x,
     ^~~~
/usr/include/c++/7/bits/unique_ptr.h:669:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types ‘std::unique_ptr<_Tp, _Dp>’ and ‘long int*’
     std::swap(m_count, other.m_count);
                                     ^
In file included from /usr/include/c++/7/bits/locale_conv.h:41:0,
                 from /usr/include/c++/7/locale:43,
                 from /usr/include/c++/7/iomanip:43,
                 from ./library/include/gambit/gambit.h:29,
                 from library/src/integer.cc:45:
/usr/include/c++/7/bits/unique_ptr.h:676:5: note: candidate: template<class _Tp, class _Dp> typename std::enable_if<(! std::__is_swappable<_T2>::value)>::type std::swap(std::unique_ptr<_Tp, _Dp>&, std::unique_ptr<_Tp, _Dp>&) <deleted>
     swap(unique_ptr<_Tp, _Dp>&,
     ^~~~
/usr/include/c++/7/bits/unique_ptr.h:676:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types ‘std::unique_ptr<_Tp, _Dp>’ and ‘long int*’
     std::swap(m_count, other.m_count);
                                     ^
In file included from /usr/include/c++/7/functional:58:0,
                 from ./library/include/gambit/shared_ptr.h:27,
                 from ./library/include/gambit/gambit.h:120,
                 from library/src/integer.cc:45:
/usr/include/c++/7/bits/std_function.h:803:5: note: candidate: template<class _Res, class ... _Args> void std::swap(std::function<_Res(_ArgTypes ...)>&, std::function<_Res(_ArgTypes ...)>&)
     swap(function<_Res(_Args...)>& __x, function<_Res(_Args...)>& __y) noexcept
     ^~~~
/usr/include/c++/7/bits/std_function.h:803:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types ‘std::function<_Res(_ArgTypes ...)>’ and ‘long int*’
     std::swap(m_count, other.m_count);
                                     ^
In file included from ./library/include/gambit/gambit.h:28:0,
                 from library/src/integer.cc:45:
/usr/include/c++/7/sstream:817:5: note: candidate: template<class _CharT, class _Traits, class _Allocator> void std::__cxx11::swap(std::__cxx11::basic_stringstream<_CharT, _Traits, _Allocator>&, std::__cxx11::basic_stringstream<_CharT, _Traits, _Allocator>&)
     swap(basic_stringstream<_CharT, _Traits, _Allocator>& __x,
     ^~~~
/usr/include/c++/7/sstream:817:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types ‘std::__cxx11::basic_stringstream<_CharT, _Traits, _Allocator>’ and ‘long int*’
     std::swap(m_count, other.m_count);
                                     ^
In file included from ./library/include/gambit/gambit.h:28:0,
                 from library/src/integer.cc:45:
/usr/include/c++/7/sstream:810:5: note: candidate: template<class _CharT, class _Traits, class _Allocator> void std::__cxx11::swap(std::__cxx11::basic_ostringstream<_CharT, _Traits, _Allocator>&, std::__cxx11::basic_ostringstream<_CharT, _Traits, _Allocator>&)
     swap(basic_ostringstream<_CharT, _Traits, _Allocator>& __x,
     ^~~~
/usr/include/c++/7/sstream:810:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types ‘std::__cxx11::basic_ostringstream<_CharT, _Traits, _Allocator>’ and ‘long int*’
     std::swap(m_count, other.m_count);
                                     ^
In file included from ./library/include/gambit/gambit.h:28:0,
                 from library/src/integer.cc:45:
/usr/include/c++/7/sstream:803:5: note: candidate: template<class _CharT, class _Traits, class _Allocator> void std::__cxx11::swap(std::__cxx11::basic_istringstream<_CharT, _Traits, _Allocator>&, std::__cxx11::basic_istringstream<_CharT, _Traits, _Allocator>&)
     swap(basic_istringstream<_CharT, _Traits, _Allocator>& __x,
     ^~~~
/usr/include/c++/7/sstream:803:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types ‘std::__cxx11::basic_istringstream<_CharT, _Traits, _Allocator>’ and ‘long int*’
     std::swap(m_count, other.m_count);
                                     ^
In file included from ./library/include/gambit/gambit.h:28:0,
                 from library/src/integer.cc:45:
/usr/include/c++/7/sstream:796:5: note: candidate: template<class _CharT, class _Traits, class _Allocator> void std::__cxx11::swap(std::__cxx11::basic_stringbuf<_CharT, _Traits, _Alloc>&, std::__cxx11::basic_stringbuf<_CharT, _Traits, _Alloc>&)
     swap(basic_stringbuf<_CharT, _Traits, _Allocator>& __x,
     ^~~~
/usr/include/c++/7/sstream:796:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types ‘std::__cxx11::basic_stringbuf<_CharT, _Traits, _Alloc>’ and ‘long int*’
     std::swap(m_count, other.m_count);
                                     ^
In file included from ./library/include/gambit/gambit.h:130:0,
                 from library/src/integer.cc:45:
./library/include/gambit/game.h: At global scope:
./library/include/gambit/game.h:843:31: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 Game ReadGame(std::istream &) throw (InvalidFileException);
                               ^~~~~
Makefile:2258: recipe for target 'library/src/integer.o' failed
make[2]: *** [library/src/integer.o] Error 1
make[2]: Leaving directory '/home/sudhan/gambit-16.0.1'
Makefile:2363: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/sudhan/gambit-16.0.1'
Makefile:1369: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cptanalatriste** [comment]
This is probably the same issue as here: https://github.com/gambitproject/gambit/issues/220
