### ISSUE TITLE
Option to suppress log output for Nash solvers

### ISSUE THREAD

**Issue by likan999** [gambitproject/gambit#238]
When calling gambit.nash.lp_solve to compute Nash equilibrium, it prints a lot of intermediate results to console. I don’t find an option to suppress it. This is a feature request that add an option to the silver to suppress those verbose intermediate results. If there are already ways to do that, then it would be nice to have them in documentations.

**Comment by tturocy** [comment]
This was dealt with in commit 700a9d74.
