### ISSUE TITLE
TypeError in Python (needs bytes-like object)

### ISSUE THREAD

**Issue by amichuda** [gambitproject/gambit#246]
Using the python implementation of Gambit, running the example code:

```
m = np.array([ [ 8, 2 ], [ 10, 5 ] ], dtype=gambit.Rational)
g = gambit.Game.from_arrays(m, np.transpose(m))
solver = gambit.nash.ExternalEnumMixedSolver()
solver.solve(g)
```

yields the following error: 
```TypeError: a bytes-like object is required, not 'str'```

writing the game to an nfg file (and stripping the newlines manually) and running it in the GUI works. Also calling the internal Python solver ```nash.enumpure_solve()``` also works.

**Comment by Altriaex** [comment]
Are you using Python 2 or Python 3. This sounds like a Python 3 String & Byte issue.

**Comment by lordflaron** [comment]
I'm using Python 3.7 currently.

**Comment by Altriaex** [comment]
> I'm using Python 3.7 currently.
> So does the library work better with Python 2?
> Is there a workaround for this error?

When calling external command line solver, gambit passes data through stdin. 
When using Python 3.x, you need to encode/decode things that go and come from stdin/stdout, which does not happen in the case of Python 2.x. At least this is what happened to me. Python 2 works for me.

In fact I am surprised that you manage to install the python api for Python 3.

**Comment by tturocy** [comment]
It is always useful to specify which version of Gambit you are using.

Gambit 16 does not support Python 3.  The current master branch does.
