### ISSUE TITLE
Error in make (first step)

### ISSUE THREAD

**Issue by dmatgol** [gambitproject/gambit#248]
Hello guys, 

I am currently doing my Masters using GT for research in airport security. However, I am a novice in Linux and I cannot build the python API (which I will need for the development of my project). I run ./configure and it gives me no error. However, when I type make and click enter I got the following error (see snapshot):
![Screenshot from 2019-03-13 18-10-32](https://user-images.githubusercontent.com/48527899/54299567-74a9d980-45bb-11e9-961e-90acd59d7455.png)

I am trying to solve this for two days. From what I understood the problem might be with the compiler but I do not have any idea on how to solve it. The compiler currently present in my laptop are (see snapshot):
![Screenshot from 2019-03-13 18-18-09](https://user-images.githubusercontent.com/48527899/54300044-5f817a80-45bc-11e9-87ea-639e2278f2f0.png)

I am working on ubuntu 18.04.2 LTS. Sorry for the simple question and I would really appreciate your help. Thank you very much!

**Comment by Altriaex** [comment]
Did you try to build it from git repository?
