### ISSUE TITLE
Failure to build the Python extension

### ISSUE THREAD

**Issue by WenjieZ** [gambitproject/gambit#250]
Python version 3.7.0

I followed the instruction [here](http://www.gambit-project.org/gambit15/build.html#build-python), but got the following error:
```
$ python setup.py build
Traceback (most recent call last):
  File "setup.py", line 32, in <module>
    m.Extension.__dict__ = m._Extension.__dict__
AttributeError: attribute '__dict__' of 'type' objects is not writable
```

**Comment by WenjieZ** [comment]
Python version 3.7.0

**Comment by Altriaex** [comment]
This is a incompatibility issue. 
I think the python extension is written in Python 2.x .
See https://stackoverflow.com/questions/40367569/dictionary-not-writable-generic-old-setup-py for a simple fix for this.

**But I will not surprise if you encounter other Python 3.x issue**

**Comment by WenjieZ** [comment]
I will have to abandon it and find other solutions. 

Btw, @Altriaex , guess [this](https://github.com/WenjieZ/Fate_GrandOrder) will interest you.

**Comment by tturocy** [comment]
When reporting an issue it is helpful to say which version of Gambit you are using.

The latest release of Gambit does not support Python 3, but the latest master in the repository does (or should).

**Comment by WenjieZ** [comment]
@tturocy, thanks for the reply. it is the current stable version 15, as you may have already correctly deduced.

**Comment by eager-seeker** [comment]
Does the "Building the Python extension" documentation for various versions state which python version is compatible? I didn't spot it if so. That might help avoid hitting the issue.

**Comment by WenjieZ** [comment]
Thanks for all the answers here. I have solved my Nash Eq problem with my own solver. If anyone is interested, it is available in my [Pokemon repo](https://github.com/WenjieZ/pokemongo). 

This ticket can be closed if the admins so wish.
