### ISSUE TITLE
"Expecting file type" error while using gambit-enumpure

### ISSUE THREAD

**Issue by cptanalatriste** [gambitproject/gambit#252]
I'm generating NFG files to later calculate its Nash equilibrium using `gambit-enumpure`. When I applied to a 500MB file, after a few seconds of processing I got the following output:

```
E:\git\bayesian-game-builder>"C:\Program Files (x86)\Gambit\gambit-enumpure.exe" huge_game.nfg
Search for Nash equilibria in pure strategies
Gambit version 15.1.1, Copyright (C) 1994-2014, The Gambit Project
This is free software, distributed under the GNU GPL

Error: line 1:2: Expecting file type
```
However, the beginning of the generated file contains its corresponding file type:

```
NFG 1 R "huge_game" { "Player_0" "Player_1" }

{{ "Type_0_action_0_Type_1_action_0_Type_2_action_0_Type_3_action_0_Type_4_action_0_Type_5_action_0_Type_6_action_0_Type_7_action_0" "Type_0_action_0_Type_1_action_0_Type_2_action_0_Type_3_action_0_Type_4_action_0_Type_5_action_0_Type_6_action_0_Type_7_action_1" "Type_0_action_0_Type_1_action_0_Type_2_action_0_Type_3_action_0_Type_4_action_0_Type_5_action_0_Type_6_action_1_Type_7_action_1" "Type_0_action_0_Type_1_action_0_Type_2_action_0_Type_3_action_0_Type_4_action_0_Type_5_action_1_Type_6_action_1_Type_7_action_1" "Type_0_action_0_Type_1_action_0_Type_2_action_0_Type_3_action_0_Type_4_action_1_Type_5_action_1_Type_6_action_1_Type_7_action_1" "Type_0_action_0_Type_1_action_0_Type_2_action_0_Type_3_action_1_Type_4_action_1_Type_5_action_1_Type_6_action_1_Type_7_action_1" 

```
When I tried to open the same file using the Gambit GUI, I obtained the "An unhanded exception occurred" error.  I don't face this problem when dealing with smaller games (50MB), can this be related to the size of the game?

**Comment by tturocy** [comment]
No, it can't have anything to do with the size of the file, given where that exception is raised.

It is very difficult to offer support without the actual file. However, what you are reporting looks inconsistent.  The parse error is occurring at character 2 of line 1, which means your file can't be starting with NFG.

**Comment by cptanalatriste** [comment]
I uploaded the [NFG file to Google Drive](https://drive.google.com/file/d/1YZHeUqMsIWxNxJIPow_P3N8Jn0vtOw9o/view?usp=sharing).

I run `gambit-enumpure` in MacOS (the previous one was over Windows) over the same file and now I obtain an empty response :

```
(base) mharman3:bayesian-game-builder carlosgavidiacalderon$ /Applications/Gambit.app/Contents/MacOS/gambit-enumpure allpay_noties_False_nojumps_False_8_valuations_auction.nfg
Search for Nash equilibria in pure strategies
Gambit version 15.1.1, Copyright (C) 1994-2014, The Gambit Project
This is free software, distributed under the GNU GPL

(base) mharman3:bayesian-game-builder carlosgavidiacalderon$ head -10 allpay_noties_False_nojumps_False_8_valuations_auction.nfg
NFG 1 R "allpay_noties_False_nojumps_False_8_valuations_auction" { "Player_1" "Player_0" }
```
It can also be opened using Gambit GUI. I suspect is a Windows issue :/

**Comment by tturocy** [comment]
I'm not able to reproduce the problem with the uploaded file, so therefore I don't think it's a Windows issue.  It really looks like there's some difference with the version of the file you're using on your Windows computers, because the parse error occurs at character 2, which really makes me think you have some other character as the first character of the file. Possible some non-printable character that gets stripped when you transmit the file?

**Comment by cptanalatriste** [comment]
I just realised I mistakingly shared the file generated from MacOS. The one generated with Windows is available here:

https://drive.google.com/file/d/1UKRaRvm0Oq3eTHAx1Y-ixzqIY_Ev5MAw/view

And here's a screenshot of the "Expecting file type" error:

![image](https://user-images.githubusercontent.com/1616531/57361692-e4c87c00-7174-11e9-9fcf-29173afc0efd.png)

Thanks again for the help :)

**Comment by tturocy** [comment]
Well, are they the same file or not?  And if they are not identical, how are they different?  That should be the answer to your question.

You'll forgive me for not wanting to try to compare two large files looking for differences.

**Comment by cptanalatriste** [comment]
There was a bug in my NFG generation code. After fixing it the error message disappeared.

**Comment by tturocy** [comment]
That's what I was thinking was the most likely - as the error message you were quoting wasn't lining up with the file.
