### ISSUE TITLE
error on macos

### ISSUE THREAD

**Issue by GeorgeDUT** [gambitproject/gambit#255]
running build
running build_py
creating build/lib.macosx-10.13-intel-2.7
creating build/lib.macosx-10.13-intel-2.7/gambit
copying gambit/enumeration.py -> build/lib.macosx-10.13-intel-2.7/gambit
copying gambit/cmdline.py -> build/lib.macosx-10.13-intel-2.7/gambit
copying gambit/gte.py -> build/lib.macosx-10.13-intel-2.7/gambit
copying gambit/__init__.py -> build/lib.macosx-10.13-intel-2.7/gambit
copying gambit/nash.py -> build/lib.macosx-10.13-intel-2.7/gambit
copying gambit/qre.py -> build/lib.macosx-10.13-intel-2.7/gambit
copying gambit/levelk.py -> build/lib.macosx-10.13-intel-2.7/gambit
copying gambit/pctrace.py -> build/lib.macosx-10.13-intel-2.7/gambit
copying gambit/profiles.py -> build/lib.macosx-10.13-intel-2.7/gambit
copying gambit/gameiter.py -> build/lib.macosx-10.13-intel-2.7/gambit
creating build/lib.macosx-10.13-intel-2.7/gambit/games
copying gambit/games/public.py -> build/lib.macosx-10.13-intel-2.7/gambit/games
copying gambit/games/contest.py -> build/lib.macosx-10.13-intel-2.7/gambit/games
copying gambit/games/__init__.py -> build/lib.macosx-10.13-intel-2.7/gambit/games
copying gambit/games/meanstat.py -> build/lib.macosx-10.13-intel-2.7/gambit/games
creating build/lib.macosx-10.13-intel-2.7/gambit/lib
copying gambit/lib/error.py -> build/lib.macosx-10.13-intel-2.7/gambit/lib
copying gambit/lib/__init__.py -> build/lib.macosx-10.13-intel-2.7/gambit/lib
running build_ext
cythoning gambit/lib/libgambit.pyx to gambit/lib/libgambit.cpp

Error compiling Cython file:
------------------------------------------------------------
...
# cython: language_level=3str
^
------------------------------------------------------------

gambit/lib/libgambit.pyx:1:0: language_level directive must be set to an integer, got '3str'

building 'gambit.lib.libgambit' extension
creating build/temp.macosx-10.13-intel-2.7
creating build/temp.macosx-10.13-intel-2.7/gambit
creating build/temp.macosx-10.13-intel-2.7/gambit/lib
cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I../.. -I../../library/include -I.. -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c gambit/lib/libgambit.cpp -o build/temp.macosx-10.13-intel-2.7/gambit/lib/libgambit.o
gambit/lib/libgambit.cpp:1:2: error: Do not use this file, it is the result of a failed Cython compilation.
#error Do not use this file, it is the result of a failed Cython compilation.
 ^
1 error generated.
error: command 'cc' failed with exit status 1

**Comment by qmaai** [comment]
I have the same problem here: on Centos with python 3. The error is exactly the same
