### ISSUE TITLE
Fail build with gcc9

### ISSUE THREAD

**Issue by yesuu** [gambitproject/gambit#258]
environment: archlinux, gcc-9.3.0

error output:
```
/usr/bin/ld: library/src/gtracer/aggame.o: in function `Gambit::gametracer::aggame::SymPayoffMatrix(Gambit::gametracer::cmatrix&, Gambit::gametracer::cvector&, double)':
aggame.cc:(.text+0x31d2): undefined reference to `Gambit::agg::AGG::doProjection(int, int, double*)'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1936：gambit-convert] 错误 1
```

I feel it is private method.

**Comment by albertjiang** [comment]
Looking at library/src/agg/agg.cc where doProjection() is defined (line 622), there's a space after AGG:: in the function signature. Does removing the space fix the error?

**Comment by lanctot** [comment]
Hi @albertjiang I am running into the same problem. Removing the space did not solve the problem, but removing the inline fixes it. I'll submit a PR.
