### ISSUE TITLE
Implement Python 3 support installation

### ISSUE THREAD

**Issue by TomoMath** [gambitproject/gambit#259]
Can I still use the usual steps to install gambit (with Python API) using 

./configure
make
sudo make install
 
The issue is that there is no configure file in 
"Implement Python3 support for gambit module".

Am I supposed to use configure.ac file somehow? or should I use configure file in the usual gambit-16.0.1 distribution?

I am using macOS Catalina 10.15.5 with Python 3.7.3.

**Comment by tturocy** [comment]
The build system is set to be re-done completely in 2021, so this will be obviated.
