### ISSUE TITLE
Failure to open agg file

### ISSUE THREAD

**Issue by ThomasCNotts** [gambitproject/gambit#264]
I'm using Gambit 15.1.1, OSX 10.15.6. When I try to open the attached file Gambit immediately closes. I have tried taking out all lines starting with # apart from the first line and the same thing happens.
[Samp.txt](https://github.com/gambitproject/gambit/files/5260385/Samp.txt)

**Comment by scottkosty** [comment]
@ThomasCNotts From what I understand, Gambit needs to work with fractions. Your decimals have a lot of significant digits so I'm guessing (not sure though) that Gambit has trouble converting them to fractions represented by a large numerator and large denominator. If you round them to the nearest whole number (just in your text editor) and then open in Gambit does it work then?

By the way, does GAMUT support extensive form games or only normal form games?

**Comment by scottkosty** [comment]
@ThomasCNotts just wanted to make sure you saw the above message. Were you able to get things working?
