### ISSUE TITLE
gambit-enumpure -P: print only distinct equilibria tuples of *actions*?

### ISSUE THREAD

**Issue by scottkosty** [gambitproject/gambit#265]
The command `gambit-enumpure -P` prints the pure strategy subgame perfect distinct equilibria strategies, however often we're interested only in the distinct tuples of equilibria *actions*. Is it possible to ask Gambit, via `gambit-enumpure -P` to print only the distinct tuples of equilibria actions?

**Comment by scottkosty** [comment]
@tturocy thanks for taking a look at this issue. I just wanted to make sure that you did not close it by mistake. Was it a poorly defined enhancement request? Or is it just difficult to achieve with the current internals of Gambit?

**Comment by tturocy** [comment]
`gambit-enumpure` should return behaviour strategy profiles if it's being passed a game in extensive form.  Do you have an example where it is not?  (There are some interactions among switches; it's possible there is some bug with some switch configurations that I'm not seeing.)
