### ISSUE TITLE
Cannot build Gambit in Ubuntu 20.04 or newer

### ISSUE THREAD

**Issue by Sacolevas** [gambitproject/gambit#270]
Hi!!

I recently installed Linux Mint 20.1 (with Ubuntu 20.04 base, which is the current LTS version); previously I had Ubuntu 18.04 LTS and could build Gambt 16.0.1 without problems installing adequate dependencies. But in a newer base like 20.04, lots of dependency errors appear during compile and installing wx-widgets packages didn't help and  couldn't install the deb packages manually. Of course, one option could be add bionic (18.04) repositories in the software sources just to be able to build gambit with the older packages but this could break a lot of things given the package dependencies that are involved. 

In consequence, the only way I could use gambit is through Wine, installing the Windows version. 

It is possible to update the source code taking this into account? Thanks in advance!

**Comment by h-v-smacker** [comment]
I managed to compile both Gambit v. 15 and v. 16 on Mint 20.1 (based on 20.04). 

This is what I had to change for version 15
in /src/libagg/agg.cc: 622 — removed "void "
in /src/libagg/agg.cc: 615, 622 — removed " " after "::"
in /src/libgambit/shared_ptr.h: 134 — removed "const "

This is what I changed for version 16 (same thing actually, just different file structure)
in /library/src/agg/agg.cc: 614 — removed "void "
in /library/src/agg/agg.cc: 607, 614 — removed " " after "::"
in /library/include/gambit/shared_ptr.h: 134 — removed "const "

After that, both versions compiled with gcc 9.3.0

**Comment by Sacolevas** [comment]
Hello! Thanks a lot!

I am not sure if I understand well, but these changes you mention are based in the links in the project website or the packages here? I downloaded 16.0.1 from the project website and also did the git clone and there are no lines like 614, 607, 614 with the info you mentioned there!

Thanks if you can help me to fix this!

**Comment by Sacolevas** [comment]
This is what I see in agg.cc from Line 601 to Line 620, for example. 

Line 601:	//apply player2's pure strat
	aggdistrib temp;
	temp.insert(make_pair(projection[actionSets[player][act]][player2][act2],1.0));
	Pr[k].multiply(Pr[k-1],temp ,numNei, projFunctions[actionSets[player][act]]);
      }
    } else {
      Pr[k].multiply (Pr[k-1], 
	projectedStrat[actionSets[player][act]][Porder[player][act][k]],
	numNei  ,projFunctions[actionSets[player][act]] ); 
    }
  }
    
}

void AGG:: doProjection(int Node, AggNumber* s)
{
  for (int i=0;i<numPlayers;i++){
    doProjection(Node,i, &(s[firstAction(i)]));
  }
Line 620: }

And this is line 134 of shares_ptr.h (this seems to be equal to yours):   void swap(const weak_ptr<T> &other)  // never throws

**Comment by h-v-smacker** [comment]
> Hello! Thanks a lot!
> 
> I am not sure if I understand well, but these changes you mention are based in the links in the project website or the packages here? I downloaded 16.0.1 from the project website and also did the git clone and there are no lines like 614, 607, 614 with the info you mentioned there!
> 
> Thanks if you can help me to fix this!

Sorry, I accidentally posted the line number for v15 as for 16, and vice versa. I edited the comment to fix that.

**Comment by Sacolevas** [comment]
Hello! I assume this is from the 16.0.1 link in the project website. I made the modifications, but I don't know how to compile. 

In my case it seems the problems are related to this: "Did not find a new enough version of wxWidgets; disabling build of
            graphical interface. "

Which wxwidgets packages in Ubuntu do I need to have installed? Using Synaptic I installed several of those, but in Ubuntu 18.04 the version was 2.8.4 I think and this seems to be causing problems!

I compiled, then .configure, make, sudo make install, I see that there are new files in /usr/local, but there is no .desktop file and cannot use the program as I wished.

**Comment by h-v-smacker** [comment]
I have these installed:

libwxbase3.0
libwxbase3.0-dev
libwxgtk3.0-gtk3
libwxgtk3.0-gtk3-dev

**Comment by Sacolevas** [comment]
Thanks a lot!!! Everything is working now! It is incredible that changing a couple of characters and some obscure lines in the source code everything works!

Now, two little questions: 

1) In the source code there is a folder in the source code with samples in /contrib/games. After compilation, is there a way to access those samples? Or you have to copy this folder into some folder in /usr/local ?

2) I compiled, I can run gambit with graphical interface, but there is no .desktop shortcut. This problem also existed when I used Ubuntu 18.04 as package base. At that time, what I did was to copy the .desktop shortcut that appeared in the source code and copy somehere in /usr/local/share/applications, although there is no application icon (I don't know where to find it). I wonder of there is a more elegant solution in this case. 

Thanks again, these are small questions compared with the huge question you helped me solve!

**Comment by h-v-smacker** [comment]
As far as I know, the contrib folder doesn't get installed at all. You probably need to edit the makefile to alter the install target, including copying the contrib folder to somewhere.

Desktop icon is fairly trivial to make, it's just a text file — take any existing one, make a copy and edit.

Also don't use "make install" — use` sudo checkinstall -D` instead. This way, you'll get it installed via the regular package system.

And no, I don't think there is a way to make gambit remember the window state.
