### ISSUE TITLE
Cannot build the Python extension issue!

### ISSUE THREAD

**Issue by thanhhng1701** [gambitproject/gambit#274]
Hello,

I got the same error as in the post: https://github.com/gambitproject/gambit/issues/273#issue-950074287, even though I already successfully installed Gambit on my /usr/local/bin following the instructions in http://www.gambit-project.org/gambit16/16.0.0/build.html . I am using Python 3.7 and macOS Mojave. 

When I tried to run the command line CFLAGS=-stdlib=libc++ python setup.py build, I got the following error:

running build
running build_py
running build_ext
skipping 'gambit/lib/libgambit.cpp' Cython extension (up-to-date)
building 'gambit.lib.libgambit' extension
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -stdlib=libc++ -I../.. -I../../library/include -I.. -I/Users/thanhnguyen/anaconda3/include/python3.7m -c gambit/lib/libgambit.cpp -o build/temp.macosx-10.7-x86_64-3.7/gambit/lib/libgambit.o
gambit/lib/libgambit.cpp:79928:40: error: use of undeclared identifier 'VERSION'
__pyx_t_1 = __Pyx_PyBytes_FromString(VERSION); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 44, __pyx_L1_error)
^
1 error generated.
error: command 'gcc' failed with exit status 1

Could you please help me with this error?
Thanks,
Thanh

**Comment by jacob-roth** [comment]
I have the same issue:
```
@JakeMBP15:python (master)$ python setup.py build
running build
running build_py
running build_ext
skipping 'gambit/lib/libgambit.cpp' Cython extension (up-to-date)
building 'gambit.lib.libgambit' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/jakeroth/opt/anaconda3/include -arch x86_64 -I/Users/jakeroth/opt/anaconda3/include -arch x86_64 -I../.. -I../../library/include -I.. -I/Users/jakeroth/opt/anaconda3/include/python3.8 -c gambit/lib/libgambit.cpp -o build/temp.macosx-10.9-x86_64-3.8/gambit/lib/libgambit.o
gambit/lib/libgambit.cpp:68910:3: warning: 'tp_print' is deprecated [-Wdeprecated-declarations]
  0, /*tp_print*/
  ^

gambit/lib/libgambit.cpp:79904:40: error: use of undeclared identifier 'VERSION'
  __pyx_t_1 = __Pyx_PyBytes_FromString(VERSION); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 44, __pyx_L1_error)

                                                ^
65 warnings and 1 error generated.
error: command 'gcc' failed with exit status 1
```

**Comment by jacob-roth** [comment]
I have a similar error. I get the below when running `python3 setup.py build`:
```
.
.
.
ry/include -I.. -I/Users/jakeroth/opt/anaconda3/envs/py39/include/python3.9 -c ../tools/lp/nfglp.cc -o build/temp.macosx-10.9-x86_64-3.9/../tools/lp/nfglp.o
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/jakeroth/opt/anaconda3/envs/py39/include -arch x86_64 -fPIC -O2 -isystem /Users/jakeroth/opt/anaconda3/envs/py39/include -arch x86_64 -I../.. -I../../library/include -I.. -I/Users/jakeroth/opt/anaconda3/envs/py39/include/python3.9 -c gambit/lib/libgambit.cpp -o build/temp.macosx-10.9-x86_64-3.9/gambit/lib/libgambit.o
gambit/lib/libgambit.cpp:79904:40: error: use of undeclared identifier 'VERSION'
  __pyx_t_1 = __Pyx_PyBytes_FromString(VERSION); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 44, __pyx_L1_error)
                                       ^
1 error generated.
error: command '/usr/bin/clang' failed with exit code 1
```

**Comment by jacob-roth** [comment]
[This](https://github.com/gambitproject/gambit/issues/273#issuecomment-895463705) fixed it: replace `VERSION` with `PY_VERSION` in line 79904 of the file `gambit/src/python/gambit/lib/libgambit.cpp`

**Comment by tturocy** [comment]
With latest `master` the Python extension build has been modernised.

Also 16.0.1 is now available via PyPI - note this is a source-only distribution on PyPI and, if you're a Windows user, who knows if it will work.  (And if you are a Windows user, also my condolences.)

**Comment by tturocy** [comment]
I'm going to close this now as per the above comment, this should now be solved.
