### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by notooth1** [gambitproject/gambit#275]
I failed to install gambit 16.0.1 on Debian 11 with this error:
```
$ make
...
./library/include/gambit/shared_ptr.h:137:37: error: no matching function for call to ‘swap(long int*&, long int* const&)’
  137 |     std::swap(m_count, other.m_count);
      |
...
```
Can anyone help?

**Comment by tturocy** [comment]
Please see e.g. #249.  Also, trying a search of issues before asking can get you even faster response...!
