### ISSUE TITLE
Removing Players in Gambit

### ISSUE THREAD

**Issue by EconJohn** [gambitproject/gambit#277]
Hi Everyone I'm new to using gambit but managed to pick it up in a few minutes. I'm wondering if its possible to remove players in the straight on interface. Specifically I'm interested in using gambit in decision analytic modelling where we have only one player and nature as a player. So if there is a way to remove the hardcoded second player that would be great.

**Comment by tturocy** [comment]
The second player is completely harmless to have in if you want to have a trivial game.  Or you can create a game yourself without one.

Gambit is intended for game-theoretic applications, and while a decision problem is a trivial example of a game, some things may not work properly if a game has only one player.  Further, there are no solution methods which take advantage of the fact that a game is in fact a decision problem - if you are only going to do very toy problems this will not matter, but for complex decision trees it might.
