### ISSUE TITLE
Removing Black lines indicating best response after calculating equilibrium

### ISSUE THREAD

**Issue by EconJohn** [gambitproject/gambit#278]
Hi everyone I am using Gambit in the context of decision analytic modelling and am wondering if there is a way to remove the black best response lines after calculating equilibrium. It seems that after the calculation is ran there is no way to remove these black lines. is there any way to deal with this?

![image](https://user-images.githubusercontent.com/53272734/132897880-8accb974-c6e2-4af8-9641-8dc60c51eedd.png)

**Comment by tturocy** [comment]
No, there is not.
