### ISSUE TITLE
Adding multiple labels under branches in Gambit

### ISSUE THREAD

**Issue by EconJohn** [gambitproject/gambit#279]
Hi I'm wondering if its possible to add more than two labels under branches. I.e I want to include expected payoff, probability of being played and action name. If there is a way to do this please let me know!

**Comment by tturocy** [comment]
No.  You can have one label above and one below.

As I noted in #277 - Gambit is targeted at game theory, and specifically at implementing Nash equilibrium calculation and parameter inference in games.  The graphical interface is there as a convenience for quick visualisation of small to medium size games.  It is quite probable it will not have the features you will want as an interactive decision analysis tool.  The graphical interface is simply a utility, not really something one would do serious work in for game theory applications.
