### ISSUE TITLE
The computation ends abnormally and there is no output for any strategic game input

### ISSUE THREAD

**Issue by wbhuangxm** [gambitproject/gambit#282]
windows 10 , gambit 16.01 and gambit 15.1.1
The program always ends with hints "The computation ended abnormally" and there is no output for any strategic game input.
I think because of this bug qre also fails for strategic game.

**Comment by tturocy** [comment]
I cannot reproduce this, and with no further details on steps to reproduce, I can't do anything more with this at this point.
