### ISSUE TITLE
Set up system for building Python wheels

### ISSUE THREAD

**Issue by tturocy** [gambitproject/gambit#297]
Especially for Windows, we should build Python wheels, as on Windows users will typically not have an appropriate C/C++ compiler installed.

This is being worked on in the 'pywheel' branch.

**Comment by tturocy** [comment]
@EwoutH I've had a go at this using cibuildwheel.  Please see the artefacts for https://github.com/gambitproject/gambit/actions/runs/1729245226, and let me know if they work for you...

**Comment by EwoutH** [comment]
```
python --version
Python 3.10.2

pip --version
pip 21.3.1

pip install "pygambit-16.0.1-cp310-cp310-win_amd64.whl"
ERROR: pygambit-16-0-1-cp310-cp310-win-amd64.whl is not a supported wheel on this platform.
```
Unfortunately it doesn't install for me.

**Comment by tturocy** [comment]
What does your platform.uname() return?

**Comment by EwoutH** [comment]
```
uname_result(system='Windows', node='EwoutMWS', release='10', version='10.0.19044', machine='AMD64')
```

**Comment by tturocy** [comment]
Well that's frustrating...  I took advantage of my son being out at swimming to try on his game computer, and that wheel installed just fine for me on a similar system:

uname_result(system='Windows', node='DESKTOP-DEQTRAK', release='10', version='10.0.19043', machine='AMD64')

So on this I really don't know what to tell you on this one, because "it works for me" is never a particularly constructive response.

**Comment by EwoutH** [comment]
Thanks for letting me know that the issue isn’t reproducible on your end. I can try some more things Tuesday.

**Comment by tturocy** [comment]
Alternatively, I have created a RC1 for 16.0.2 on PyPI; you could try `pip install pygambit==16.0.2rc1` as well.

If at some point you want to work with the bleeding edge you'll need to build from git of course, but if not needed then perhaps this just solves the problem rather than trying to figure out why your system doesn't like that particular wheel.

**Comment by tturocy** [comment]
I'm closing this now because we've got wheels building in the CI, and I have a few reports of successful installs off of PyPI.

**Comment by EwoutH** [comment]
Thanks for the efford! I'm on vacation untill next week, so had not time to test  but I do appreciate it!
