### ISSUE TITLE
Setting payoffs - TypeError: Must use a tuple of ints, strategy labels, or strategies

### ISSUE THREAD

**Issue by manuelmontesinos** [gambitproject/gambit#307]
Hi there, 

I am using the Python interface to build and solve a game (running on Python 3.9.7, Windows 10). I am trying to set the payoffs of a set of games with the code below. For a given game `g`, I define the number of players in `number_of_players`, and the number of possible outcomes in `number_of_outcomes`. I also define all the possible outcomes of `g` in a two-dimensional numpy array called `outcomes`, where there are as many rows as outcomes, and as many columns as players. I understand that I need to convert each row of this array into a tuple of integers for the code to work. For this purspose I use `numpy.ndarray.astype`:

```python
for ii in range(number_of_players):
        for io in range(number_of_outcomes):
            g[tuple(outcomes[io, :].astype(int))][ii] = 0
```

However, when I run the code, I get the error below, which I do not understand, because I am feeding `g[.][ii]` with a tuple of integers. The code runs through if I write, for instance, `g[0,0][ii] = 0`. Is there any workaround for this problem? 

```
Traceback (most recent call last):
  g[tuple(outcomes[io, :].astype(int))][ii] = 0
  File "pygambit\lib\game.pxi", line 340, in pygambit.lib.libgambit.Game.__getitem__
TypeError: Must use a tuple of ints, strategy labels, or strategies
```

**Comment by tturocy** [comment]
Please as always provide *complete* code that demonstrates the issue.  The above is not sufficient to reproduce this.

Having said that, `Game.from_arrays` does exactly this for you already, I think.

**Comment by manuelmontesinos** [comment]
Sorry for that. Here is an example of what I am saying:

```python
import numpy as np
import pygambit

outcomes =  np.array([[0., 0.], [1., 0.], [2., 0.], [3., 0.], [0., 1.], [1., 1.], [2., 1.], [3., 1.]])
number_of_outcomes = outcomes.shape[0]
number_of_players = outcomes.shape[1]
number_of_strategies = [4]*number_of_players

g = pygambit.Game.new_table(number_of_strategies)

for ii in range(number_of_players):
        for io in range(number_of_outcomes):
            g[tuple(outcomes[io, :].astype(int))][ii] = 0
```

**Comment by manuelmontesinos** [comment]
Just in case someone else stumbles upon the same problem, I managed to make my code work with a little twist to put each row of the matrix of outcomes into a list of integers and converting this list into a tuple, like this:

```python
import numpy as np
import pygambit

outcomes =  np.array([[0., 0.], [1., 0.], [2., 0.], [3., 0.], [0., 1.], [1., 1.], [2., 1.], [3., 1.]])
number_of_outcomes = outcomes.shape[0]
number_of_players = outcomes.shape[1]
number_of_strategies = [4]*number_of_players

g = pygambit.Game.new_table(number_of_strategies)

for ii in range(number_of_players):
        for io in range(number_of_outcomes):
            t = [int(ip) for ip in outcomes[io, :]]
            g[tuple(t)][ii] = 0
```

**Comment by tturocy** [comment]
Yes.  The error message was fully correct.  The type of the elements in `outcomes[io, :].astype(int)` is `numpy.int64`, not `int`.

All that said, actually the correct way to accomplish creating a game like this would be to use `Game.from_arrays` as noted above.
