### ISSUE TITLE
Assertion on "Insert Move"

### ISSUE THREAD

**Issue by mdnahas** [gambitproject/gambit#310]
I'm on Ubuntu 20.04.4 LTS.   I tried to complie with source 16.0.1 from SourceForge.  That would not compile.

I tried again with the git repo.  I got an assertion on the first thing I did.

My steps:
1. git clone https://github.com/gambitproject/gambit.git
2. ./configure --prefix=/opt
...WARNING: Did not find a new enough version of wxWidgets;
3. cursed loudly
4. Download wxWidgets-3.2.0 source code, unzip, cd to directory
5. mkdir gtk-build
6. cd gtk-build
7. ../configure --prefix=/home/mike/src/wx-install --disable-shared
8. make -j7
9. sudo make install
10. cd back to gambit directory
11. ./configure --with-wx-prefix=/home/mike/src/wx-install --prefix=/opt
12. make
13. sudo make install
14. /opt/bin/gambit
<GUI window opens>
15. selects node "u"
16. Edit -> Insert Move
../src/common/sizer.cpp(2288): assert "CheckSizerFlags(!((flags) & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL | wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL)))" failed in DoInsert(): wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL | wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL will be ignored in this sizer: wxEXPAND overrides alignment flags in box sizers

DO NOT PANIC !!

If you're an end user running a program not developed by you, please ignore this message, it is harmless, and please try reporting the problem to the program developers.

You may also set WXSUPPRESS_SIZER_FLAGS_CHECK environment variable to suppress all such checks when running this program.

If you're the developer, simply remove this flag from your code to avoid getting this message. You can also call wxSizerFlags::DisableConsistencyChecks() to globally disable all such checks, but this is strongly not recommended.
../src/common/sizer.cpp(2288): assert "CheckSizerFlags(!((flags) & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL | wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL)))" failed in DoInsert(): wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL | wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL will be ignored in this sizer: wxEXPAND overrides alignment flags in box sizers

DO NOT PANIC !!

If you're an end user running a program not developed by you, please ignore this message, it is harmless, and please try reporting the problem to the program developers.

You may also set WXSUPPRESS_SIZER_FLAGS_CHECK environment variable to suppress all such checks when running this program.

If you're the developer, simply remove this flag from your code to avoid getting this message. You can also call wxSizerFlags::DisableConsistencyChecks() to globally disable all such checks, but this is strongly not recommended.

**Comment by mdnahas** [comment]
I tried:

$ set WXSUPPRESS_SIZER_FLAGS_CHECK=1 
$ export WXSUPPRESS_SIZER_FLAGS_CHECK
$ gambit

Still produces same assertion.

**Comment by tturocy** [comment]
wxWidgets-3.2 is only recently released and, annoyingly, appears to have some differences in behaviour from the last 3.1.x series.

**Comment by mdnahas** [comment]
Downloaded wxWidgets 3.1.7.   Compiled into static library in $HOME/src/wx-install-3.1.7.

$ export PATH="$HOME/src/wx-install-3.1.7/bin:$PATH"
$ ./configure --prefix=/opt

Identifies the wxWidgets version as 3.1.7.

$ make

Traverses the directories but doesn't recompile anything!

$ sudo make install
$ /opt/bin/gambit

Problem still exists.  (But this is due to make not recompiling with the new libraries.)

$ make clean
$ make

Make recompiles using the 3.1.7 libraries

$ /opt/bin/gambit

Problem still exists!

$ export WXSUPPRESS_SIZER_FLAGS_CHECK=1
$ /opt/bin/gambit

Problem goes away.   So, at least with wxWidgets 3.1.7, I am able to suppress the "assert CheckSizerFlags..." warning with the environment variable, as the warning says it can.  

Now, I am able to use Gambit without warning dialogs popping up all the time.  But I wouldn't call my problem "solved", since it requires setting an environment variable.
