### ISSUE TITLE
Unable to compile 16.0.1 on Ubuntu

### ISSUE THREAD

**Issue by mdnahas** [gambitproject/gambit#311]
I'm running Ubuntu 20.04.4.  I was unable to compile 16.0.1 source downloaded from SourceForge

1. I downloaded 16.0.1 source from SourceForge. 
2. ./configure --prefix=/opt
3.  make
... quickly generates this error:
g++ -DHAVE_CONFIG_H -I.  -I./src -I./library/include -I./src/labenski/include -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread   -g -O2 -MT library/src/integer.o -MD -MP -MF $depbase.Tpo -c -o library/src/integer.o library/src/integer.cc &&\
mv -f $depbase.Tpo $depbase.Po
In file included from ./library/include/gambit/gambit.h:120,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h: In member function ‘void Gambit::weak_ptr<T>::swap(const Gambit::weak_ptr<T>&)’:
./library/include/gambit/shared_ptr.h:137:37: error: no matching function for call to ‘swap(long int*&, long int* const&)’
  137 |     std::swap(m_count, other.m_count);
      |                                     ^
In file included from /usr/include/c++/9/bits/nested_exception.h:40,
                 from /usr/include/c++/9/exception:144,
                 from /usr/include/c++/9/ios:39,
                 from /usr/include/c++/9/ostream:38,
                 from /usr/include/c++/9/iostream:39,
                 from library/src/integer.cc:37:
/usr/include/c++/9/bits/move.h:182:5: note: candidate: ‘template<class _Tp> typename std::enable_if<std::__and_<std::__not_<std::__is_tuple_like<_Tp> >, std::is_move_constructible<_Tp>, std::is_move_assignable<_Tp> >::value>::type std::swap(_Tp&, _Tp&)’
  182 |     swap(_Tp& __a, _Tp& __b)
      |     ^~~~
...
which looks similar to this issue: [https://github.com/gambitproject/gambit/issues/249](https://github.com/gambitproject/gambit/issues/249)

**Comment by tturocy** [comment]
The latest release is 16.0.2.  First can you confirm this is still a problem with the latest release?

**Comment by mdnahas** [comment]
Compilations works for 16.0.2 with statically linked wxWidgets 3.2.0.0.  Running the program has the same problem as I identified in another issue.  I noticed a different problem with the release of 16.0.2 -- it is missing the INSTALL file.  When I used the tool "meld" ("diff" with a GUI) I noticed README and possibly other files missing.  

**Original problem solved.**

**Recommendation** It would be nice if the make command was safe for multiple cores.  I imagine "make -j8" would build much faster on my 8 core machine.  But having written Makefiles myself, I don't trust they're multi-core safe unless the author tells me so.  If it is safe to do, please change INSTALL to use the command "make -j`nproc`".  

**New problem:** Duplicate of #310 

**New problem:** gambit-16.0.2.tar.gz downloaded from https://sourceforge.net/projects/gambit/files/gambit16/16.0.2/ is missing README, INSTALL, and possibly other files.
