### ISSUE TITLE
Unable to compute any equilbria from GUI

### ISSUE THREAD

**Issue by mdnahas** [gambitproject/gambit#313]
I'm running 
commit c0fbc7e3634a4c2ae154ff7a61fb088605ecb7f3
wxWidgets version 3.1.7
on Ubuntu Linux 20.04.4 LTS

I start gambit,
create a simple extensive game  
choose "Compute Nash equilbria"
leave the default options and click "ok"

A new window pops up with the red text "The computation ended abnormally".

If I choose "Compute Nash equilibria" and select non-default options, the same result happens.

Here's the simple extensive game I used.   I changed the extension to ".txt" so that Github accepts it.
[simple_example.txt](https://github.com/gambitproject/gambit/files/9396963/simple_example.txt)

**Comment by mdnahas** [comment]
Same result happens with gambit 16.0.2.
(also with static compiled wxWidgets 3.1.7)

**Comment by mdnahas** [comment]
I did:

$ export PATH="/opt/bin:$PATH"

Then reran gambit, loaded the file, and clicked "Compute Nash equilibria".   

And it worked.

So the bug is that Gambit relies on the PATH variable and fails with a meaningless error when its programs cannot be found in the PATH.  

It is your project, but I would fix this by making Gambit into a single binary.  Many programs have a single binary that does multiple things (e.g., git, tar, etc.).  Not only would this problem go away, but it would be easier for your users to share Gambit with others.  But, as I said, it's your project and it's probably quicker to just insert a more intuitive error message.

**Comment by tturocy** [comment]
This architecture is a conscious design decision.  It is done for good reasons and is the correct way to do it.

The GUI is a convenience for running the command-line solvers.  The command-line solvers "are" Gambit, not the GUI.  The GUI is, functionally, like an IDE - and IDEs do not compile all of their tools into the binary.  Having them be separate is essential for, for example, reproducibility of runs.

**Comment by mdnahas** [comment]
You've reject my solution to this bug, but there are many possible other solutions to this bug.  The bug is "The GUI depends on the PATH and, if that is set wrong, the GUI doesn't provide a useful error message that tell the user how to fix it."  

Other solutions for it include:

- improve the error message when a solver is not in the PATH.
- at startup, check that the solvers are in the PATH at startup and create a pop-up window with a warning
- determine the directory that the GUI was run from and add that to the front of the PATH environment variable
