### ISSUE TITLE
3 warnings while compiling python extension

### ISSUE THREAD

**Issue by mdnahas** [gambitproject/gambit#315]
While I ran "cd src" followed by "python3 setup.py build" and got the following warnings.  I'm pretty sure that last one is not a problem.  I don't know about the first two.   

I'm using the Github repo, commit c0fbc7e3634a4c2ae154ff7a61fb088605ecb7f3 .

solvers/gtracer/gnm.cc: In function ‘int Gambit::gametracer::GNM(Gambit::gametracer::gnmgame&, Gambit::gametracer::cvector&, Gambit::gametracer::cvector**&, int, double, int, int, double, bool, double, bool)’:
solvers/gtracer/gnm.cc:410:10: warning: ‘s_hat’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  410 |  if(B[i] && i != s_hat) {
solvers/gtracer/gnm.cc:408:15: warning: ‘n_hat’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  408 |     if(s[n_hat] == s_hat)

solvers/gtracer/cmatrix.cc: In member function ‘int Gambit::gametracer::cmatrix::LUdecomp(Gambit::gametracer::cmatrix&, int*) const’:
solvers/gtracer/cmatrix.cc:114:9: warning: ‘imax’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  114 |   ix[j] = imax;
      |   ~~~~~~^~~~~~

**Comment by tturocy** [comment]
These are known (this is third party code we package) and are harmless.
