### ISSUE TITLE
Documentation on how to install Python extension needs edits

### ISSUE THREAD

**Issue by mdnahas** [gambitproject/gambit#316]
I installed python and suggest some changes to the documentation.  

I was following the documentation here, for 16.0.2:
https://buildmedia.readthedocs.org/media/pdf/gambitproject/latest/gambitproject.pdf
But it looks to be the same in doc/build.rst

In section 2.7.7 "Building the Python extension"
- "setup.py" is in "src/" not in "src/python".
- I used "python3" on the commandline.   So, "python3 setup.py build".   (For my setup, "python" is python 2.7.18.)
- To install, I ran "python3 setup.py install --user".  "setup.py" was trying to write to "/usr/local/lib" (instead of "/opt" as I had passed to ./configure).   You might consider adding this per-user install as an option in the documentation.  
- The tests are in "src/pygambit/tests" (not "src/python/gambit/tests")
- to use the package in a python program, you write "import pygambit" (not "import gambit")

**Comment by tturocy** [comment]
Revised ef732c81
