### ISSUE TITLE
GUI Feature requests

### ISSUE THREAD

**Issue by mdnahas** [gambitproject/gambit#317]
I played with Gambit for a while and I have some suggested improvements to the user interface.  These are all just first impressions, but if you want to make the tool friendly to new users, these comments should be useful.  

I was running Gambit 16, commit c0fbc7e3634a4c2ae154ff7a61fb088605ecb7f3 with wxWidgets 3.1.7 on Ubuntu Linux 20.04.4.

- Gambit doesn't support common command-line options like "--version" and "--help".   (It also doesn't have a man page, but that seems less important.)

- The "current node" is identified by filled circle that is slightly larger than other nodes.  This is difficult to see.  I suggest changing it to a hollow circle around the node (with a visible gap between the hollow circle and the filled circle that represents the node).

- I must be very precise to select a node.  The click must be in the filled circle.  Sometimes, the filled circle isn't even enough --- _it must be in the very center of the filled circle_!   

- The arrow keys do not work to change the selected node.  

- The "delete" key does not delete a node's subtree.  

- In general, I like to use the keyboard to quickly edit things.  Gambit doesn't seem to really support that.  That's fine for new users, but it's something to think about if you have power users.  

- It took me a while to figure out how to rename edges and change the probability of chance moves.  It requires selecting a node and then selecting "Move properties".  It seems strange that, if I'm selecting a node, it isn't part of "node properties".

- The GUI does not give a warning if a chance node's move probabilities do not sum to 1.  

- The chance player has information sets.  That seems odd to me.   

- I could not figure out how to set the payouts.  When I right click and select Node Properties, the "Outcome" options are just "(null)" and I could not figure out a way to type new ones.   I had to read the documentation to find out that I should double click on the "(u)".  This is not at all obvious.

- If you delete a payout (set it to the empty string and hit enter), there doesn't seem to be any way to edit it!   (I did this when I accidentally edited the payout on a non-final node, so this is a real usage, not a testing the limits of the UI!)  I eventually got out of the problem by editing Node Properties and selecting the outcome "(null)".  Still, there should be a warning or it should not be allowed at all.

- When typing a new payout, the text entry box is 1-character wide.  I could not see the number I was typing.

- When typing a payout for Player 1, the "tab" key moves the cursor to the text entry box for the payout for Player 2.  That's great!!!  Keep that!   But I also wish that "tab" in the one for Player 2 moved me to the next unset payout in the tree.  Then I could enter a lot of them at once.

- The "reduced strategic representation" of the game displays numbers as fractions.  It would be nice to see those as decimals.  (Or at least have the option to see them as that.)

- After clicking "Compute Nash equilibria" and closing the resulting pop-up window, the bottom of the main window is used to display the equilbria.  That is, there is a split window with the bottom saying "[Profiles 1]  All equilibria by enumeration ....".   My problem was that I couldn't close the split window view.  I could adjust the size of the bottom, but not close it.   I'm using a small laptop screen and real estate is valuable. 

- When I saved my Gambit workbook, it had no filename extension.  That is, if I select "Save as", type "test" and hit "enter", Gambit writes a file named "test" not "test.gbt".  If the user does this, it should write "test.gbt".  If the user tries to write a file with no extension, there should be a pop-up asking "are you sure?".

- When loading files, "all files" should be "*" _not_ "*.*".  When I saved the files without any extension, I could not load them because there was no "." in the filename.     

- When loading a file, a new window is created and the original window stays open.  That's a fine behavior.  But, if you want to look a little more professional, if the original window doesn't have anything in it, you can close it.

- Labels are inconsistent.  In the game tree, "1:1" refers to Player 1, Information Set 1.  In the equilibrium result, "1:1" refers to "Information Set 1, Move 1".  It took me a good 5 minutes to figure out how to interpret the equilbria.   Perhaps Gambit should not use arabic numbers for Players, Information Sets, _and_ Moves.  Other options are roman numerals, capital letters, and lower-case letters.  I'd probably recommend using capital letters for Information Sets.

- When I click on an equilibrium, the tree changes so that a black line is drawn to show the moves that each player would take at each node.  I'm not a fan of the black line.  It is hard to see against blue (the default color for Player 2).  Perhaps the line for each move could stay the same color, but the chosen moves could be drawn 2 or 3 times wider instead?   Personally, I want to focus most on the paths that go from the root all the way to payoff.   Perhaps those should be drawn 3 times as wide and the other, off-path chosen moves, should be 2 times the normal width?

- When clicking on a move in an equilbrium, gambit prints new information under "Player 1" and "Player 2" in the top window.  The Payoff values are fractions.  Since I typed my payoffs as decimals, it would be nice to have decimals there.  (Or at least the option to be decimals.)

**Comment by mdnahas** [comment]
Regarding the display of equilbria, it seems the black lines are drawn such that the length of the line indicates the probability that that branch is taken.  So, the length of the black line is important.  Just changing the width of the line is not sufficient.  So, reject my solution for that issue.  But the issue exists --- it is hard to see the black line against the blue lines used as the default color for Player 2.

**Comment by tturocy** [comment]
We'd welcome contributions of pull requests which implement ideas.  However, a long list of undifferentiated suggestions is not an effective way to progress matters.  At the moment, we do not have spare resource to implement functionality changes to the graphical interface.
