### ISSUE TITLE
Documention bug: It is difficult to select solver for game

### ISSUE THREAD

**Issue by mdnahas** [gambitproject/gambit#318]
I'm trying to analyze many games and I want to call gambit via a script.  Gambit has many solvers.  I have no idea which to select.

The documentation tells me, for each solver:

- the method it uses
- the research paper it is based on
- what code it was based on
- command-line options for the solver.  

But the documentation doesn't provide me the information I need to pick which one to use.  The documentation should be written for the user, not a historian or programmer.  

The things I'm looking for for each algorithm include:

- Does this solver work with more than 2 players?  
- Does it find all equilibria or just 1 equilibria?  
- Does it behave differently with extensive vs. strategic games?
- Are there specific cases where an algorithm does not return an answer?
- Do its results contain any imprecision?  E.g., they're only accurate to .001 or something.
- What is the expected runtime??

And for all algorithms:

- Which algorithm is recommended (which might depend on the users' situations)?
- Will 2 different algorithms always produce the same results (up to a certain level of precision)?  
- Is it ever worthwhile to run multiple algorithms?

Right now, I'm reading src/gui/dlnash.cc to figure out what Gambit's GUI's "recommended solver" is.   That seems to be the best answer I can find at the moment.

**Comment by tturocy** [comment]
As far as I can see all of this information is in

https://gambitproject.readthedocs.io/en/latest/tools.html

The objective of the documentation of a package is to document the package.  Look, for example, to the documentation of SciPy; it describes the algorithms and facilities offered, but does not provide a complete tutorial that covers every use case.  There exist survey papers which cover some practical aspects of algorithm selection or compare running times.

**Comment by mdnahas** [comment]
I would say that documentation exists to help the user. 

For my use, I just wanted to enter a game and find the equilbria.  I don't care about which algorithm is used, just like I don't care which algorithm scipy uses inverts a matrix.  In fact, scipy's documentation doesn't say which algorithm it uses.  

It is worth thinking about who the user of the software is, how much they know, and what you expect of them.   You can say that I'm not the target user of Gambit.  But, if I am, I'm just letting you know that I encountered a problem with using the tool and the lengths I had to go to solve my problem.  And it was a lot.
