### ISSUE TITLE
Inconsistency in return type of pygambit solve methods

### ISSUE THREAD

**Issue by mdnahas** [gambitproject/gambit#320]
I'm getting bad output from ExternalEnumMixedSolver in pygambit.  I think this happens in the GUI too.

I've attached the "simple poker game" that I was using.  You'll have to change the file extension from "txt" to "efg" to load it into Gambit.

>>> import pygambit
>>> g = pygambit.Game.read_game("pygambit_example.efg")
>>> solver = pygambit.nash.ExternalEnumMixedSolver()
>>> solver.solve(g)
[<NashProfile for 'A simple poker example': [[0.3333333333, 0.6666666667, 0.0, 0.0], [0.6666666667, 0.3333333333]]>]

The output is strange because of "0.0, 0.0", which I believe need to sum to 1.

This output is different from the other 3 solvers I tried.  Not only do the pairs of values sum to 1 but the structure of the output (lists in pygambit) is different.  The other solvers' outputs look nearly identical.  

>>> solver = pygambit.nash.ExternalEnumPolySolver()
>>> solver.solve(g)
[<NashProfile for 'A simple poker example': [[[1.0, 0.0], [0.3333333333, 0.6666666667]], [[0.6666666667, 0.3333333333]]]>]
>>> solver = pygambit.nash.ExternalLogitSolver()
>>> solver.solve(g)
[<NashProfile for 'A simple poker example': [[[1.0, 0.0], [0.33333362892950247, 0.6666663710704975]], [[0.6666668883629998, 0.3333331116370002]]]>]
>>> solver = pygambit.nash.ExternalLPSolver()
>>> solver.solve(g)
[<NashProfile for 'A simple poker example': [[[1.0, 0.0], [0.3333333333, 0.6666666667]], [[0.6666666667, 0.3333333333]]]>]

[pygambit_example.txt](https://github.com/gambitproject/gambit/files/9445945/pygambit_example.txt)

**Comment by mdnahas** [comment]
What I'm seeing is that one solver produces "mixed strategies" and another produces "behaviors" (probabilities for moves at each information set).  So, the output type is inconsistent.

I consider this a bug.  First, it took me a long time to figure out.  Second, I need to write my code based on 2 different return types by a solver.  (And the top-level return type is "list" for both results!)   

Having both classes named "Solver" and having methods named "solve" that have 2 different return types is not helpful to users.  I'd suggest having two methods named "solveForEquilbriumStrategies()" and "solveForEquilbriumBehaviors()".  Or some other similar way to differentiate between the two.

**Comment by tturocy** [comment]
This has been the case since 1997 and has caused no problems.  At least in games of perfect recall there is an immediate interchangeability between the representations.

We respect that others may have different preferences for how an API is laid out, but one person's preference is not enough to introduce breaking changes.
