### ISSUE TITLE
Feature request: support for +/- infinity

### ISSUE THREAD

**Issue by mdnahas** [gambitproject/gambit#322]
I'm an economist using a very common utility function: log().   When a player has 0 items, I would like their playoff to be log(0) = -infinite.  

In pygambit, when I do:

o = g.outcomes.add("foo")
o[0] = float("-inf")
o[1] = math.log(10)

I get the following error:
 File "pygambit/lib/outcome.pxi", line 99, in pygambit.lib.libgambit.Outcome.__setitem__
 TypeError: payoff argument should be a numeric type instance

**Comment by mdnahas** [comment]
I tried replacing 
    float("-inf") 
with 
   -sys.float_info.max
which is equal to:
    -1.7976931348623157e+308

And got the same error!

**Comment by mdnahas** [comment]
-Decimal('Inf')
Also fails.  

I'm now just using negative 1 billion.

**Comment by tturocy** [comment]
This is regrettably not a coherent proposal.  Every solution method requires that all payoffs are real numbers.

I would not even know how to interpret a game in which an infinite payoff appeared - I have never, ever seen one.  Utility is always, always, always a function from outcomes to the real numbers.

**Comment by mdnahas** [comment]
I've seen a few sites describing the game "Mutually Assured Destruction" with negative infinity payoffs.

https://blogs.cornell.edu/info2040/2019/09/18/game-theory-in-the-cold-war/

And, as I said, many common utility functions in economics have negative infinity as a possible value. 

Still, I understand that the algorithms may not consider it due to the mathematical statement of the problem or numerical concerns.
