### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by EwoutH** [gambitproject/gambit#324]
Hi @tturocy!

Would it be possible to tag a new release of gambit? There are some nice new features since 16.0.2, and having an improved wxWidgets 3.2 interface is also great. Further more, having Python 3.11 wheels on PyPI would also be great, which happens automatically when you tag a new release! (since cibuildwheel now builds them by default)

**Comment by EwoutH** [comment]
I also opened a PR to automatically deploy Python wheels to PyPI once a tag is created: #325

**Comment by tturocy** [comment]
Many thanks for these.  The pause in not doing a release is in part because we have been focusing on a funding opportunity, on which we hope there will be news to share soon.

**Comment by EwoutH** [comment]
Sounds awesome! Being funded to spend some serious time on a project helps so much.

If it isn't [NumFOCUS](https://numfocus.org/), you should also look into NumFOCUS!
