### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by baskuit** [gambitproject/gambit#331]
I have observed consistent memory leaks in pygambit and in the portion of the C++ source that I have imported into my project.
I suspect that these may have the same cause, since I only used the enummixed solver with both.

The python code that produces the leak is below. I don't believe its related, but the way I create a game is janky. However I could not find another way
```
  def _solve(self, M: torch.Tensor, max_actions=2):
          rows, cols = M.shape[:2]
          pygambit_matrix = np.zeros((rows, cols), dtype=pygambit.Decimal)
          for _ in range(rows):
              for __ in range(cols):
                  pygambit_matrix[_][__] = pygambit.Decimal(M[_][__].item())
          # iirc pygambit is kinda finicky
  
          g = pygambit.Game.from_arrays(pygambit_matrix, -pygambit_matrix)
  
          solutions = [
              [S[_] if _ < rows else 0 for _ in range(max_actions)]
              + [S[rows + _] if _ < cols else 0 for _ in range(max_actions)]
              for S in pygambit.nash.enummixed_solve(g, rational=False)
          ]
```

My C++ that produces the leak is below.
```
    void solve_bimatrix(
        Linear::Bimatrix2D<double, MatrixUCB::state_t::size_> bimatrix)
    {
        Game game = build_nfg(bimatrix);
        shared_ptr<EnumMixedStrategySolution<double>> solution = solver.SolveDetailed(game);
        // List<List<MixedStrategyProfile<double>>> cliques = solution->GetCliques();
        // PrintCliques(cliques, renderer);
        // delete game;
    }

    Game build_nfg(
        Linear::Bimatrix2D<double, MatrixUCB::state_t::size_> bimatrix
        )
    {
        Array<int> dim(2);
        dim[1] = bimatrix.rows;
        dim[2] = bimatrix.cols;

        GameRep *nfg = NewTable(dim);
        // Assigning this to the container assures that, if something goes
        // wrong, the class will automatically be cleaned up
        Game game = nfg;

        StrategyProfileIterator iter(StrategySupportProfile(static_cast<GameRep *>(nfg)));

        for (int i = 0; i < bimatrix.rows; ++i)
        {
            for (int j = 0; j < bimatrix.cols; ++j)
            {
                (*iter)->GetOutcome()->SetPayoff(1, std::to_string(bimatrix.get0(i, j)));
                (*iter)->GetOutcome()->SetPayoff(2, std::to_string(bimatrix.get1(i, j)));
                iter++;
            }
        }

        // game->Write(std::cout);
        return game;
    }
```
NOTE: If the `delete game;` line above is un-commented then there is no leak. If the game is not manually deleted, then the leak will persist, even if I comment out 
`shared_ptr<EnumMixedStrategySolution<double>> solution = solver.SolveDetailed(game);`
It would appear that in enummixed.cc, the leak is caused by line 141 `Game game = ReadGame(*input_stream);`.
This game object is not manually deleted and it occurs within a while loop. I'm guessing Game is not a smart pointer?

**Comment by tturocy** [comment]
`Game` is (intended to be) a smart pointer.  However, the game representation code is very old; it predates the existence of e.g. the smart-pointer implementations in STL.  (Actually it predates STL.)  In effect, there are places where the equivalent of a `weak_ptr` should be used, but the implementation is not fully correct.  When the code was written it was not being exposed to general use, and things were always done in an order where this was not a problem.

The implementation of game representations is being completely overhauled in the coming months which will render the underlying issue here moot.  So even though this is a legitimate issue, it's not practical to do anything about it (it is more than a one-line fix) as the code will just be removed anyway.

**Comment by baskuit** [comment]
ok thanks for response.
