### ISSUE TITLE
pygambit does not handle NFG files with null outcomes correctly

### ISSUE THREAD

**Issue by AbhijeetKrishnan** [gambitproject/gambit#403]
MRE below -

```python
import pygambit as gbt

s = """
NFG 1 R "" { "1" "2" }

{ { "" "" }
{ "" "" }
}
""

{
{ "" 0, 0 }
{ "" 0, 0 }
{ "" 0, 0 }
{ "" 0, 0 }
}
0 0 0 0
"""

game = gbt.Game.parse_game(s)
game[0, 0]
```

This causes the following error -

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/pygambit/outcome.pxi", line 36, in pygambit.gambit.Outcome.__repr__
    f"<Outcome [{self.outcome.deref().GetNumber()-1}] '{self.label}' "
RuntimeError: Dereferenced null pointer
```
In this case, I'm trying to get the payoff for contingency (0, 0), so I expect to get 0.

The issue is in [`src/games/file.cc:691`](https://github.com/gambitproject/gambit/blob/90bbf7c1b8f79b30747a89710600ad2bd9d5acca/src/games/file.cc#L595C16-L595C16). While parsing the NFG file, an ID of 0 is [assigned](https://github.com/gambitproject/gambit/blob/90bbf7c1b8f79b30747a89710600ad2bd9d5acca/src/games/gametable.cc#L89) a `nullptr`. This makes sense according to the [game representation](https://gambitproject.readthedocs.io/en/v16.0.2/formats.html?highlight=null#structure-of-the-body-list-of-outcomes), but there's no check when calling [`outcome.deref()`](https://github.com/gambitproject/gambit/blob/90bbf7c1b8f79b30747a89710600ad2bd9d5acca/src/pygambit/outcome.pxi#L36) in Python.

**Comment by tturocy** [comment]
Generating an exception here certainly isn't correct.  We've added a fix in d32b8b4, so `game[0, 0]` now correctly returns `None` and therefore no exception is raised.

src/games/file.cc:691 is correct.  Strategic game contingencies are treated as de-facto equivalent to terminal nodes of an extensive game, and therefore null outcomes are permitted.  Contingencies with null outcomes are treated as resulting in payoffs of zero for all players, but they are null objects, not proper outcomes.

An alternate formulation of outcome would be as equivalence classes of contingencies/nodes.  It's something we've thought about, but it's not the way they are currently defined.

**Comment by AbhijeetKrishnan** [comment]
I'm not sure what the difference is between a null outcome vs an outcome with 0 payoff for both players. The former occurs when I generate NFG files using the Gambit GUI. For the same payoffs, pygambit will produce unique outcome IDs (>0) for even 0-payoff nodes, which allows me to get 0 when I do `game[0, 0]`. Why is there a difference between the NFG files produced by the Gambit GUI and pygambit?

**Comment by tturocy** [comment]
A null outcome is a null outcome!  In the context of a game tree, it means there's no incremental payoff associated with reaching that node.  A strategic game is just a trivial game tree, so it means the same thing there.

Functionally, it is a convenient way of representing sparsity.

The graphical interface is consistent with the Python - it is doing the equivalent of .from_arrays with arrays of all zero.  Graphical interfaces are by their nature intended to be a simplified interface.  The typical graphical interface user doesn't need to deal with the possibility that two or more cells in a strategic game could be logically the "same" outcome.  The Python exposes a richer interface that allows users more control over the representation of the game.
