### ISSUE TITLE
BUG: `gambit-gnm` returns "oops" for single-profile payoff matrix.

### ISSUE THREAD

**Issue by wyz2368** [gambitproject/gambit#405]
Remark the issue when using “gnm” for solving NE: if the payoff matrix only has one cell with payoff (0, 0) for two-player games, then “gnm” will return “oops”.

**Comment by tturocy** [comment]
A minimal example in Python to reproduce this:

```
import pygambit as gbt
g = gbt.Game.new_table([1,1])
gbt.nash.gnm_solve(g)
```

This appears to occur with any game where all payoffs are zero.  The "oops" is coming from the routine which computes the adjoint of a matrix.

**Comment by tturocy** [comment]
From 80d4d26, the "oops" has been replaced with generating an exception - this does not fix the problem fully but at least now it fails in a proper way.
