### ISSUE TITLE
From a behavior strategy profile to numpy

### ISSUE THREAD

**Issue by keinccgithub** [gambitproject/gambit#415]
Gambit provides convenient operators that read the data from numpy.array in Python's package NumPy.
However, there may be some difficulties when transferring the outcome MixedBehaviorProfile to numpy.array.
In detail, I get one Norm-form game's Nash equilibirium as:
`[[0.33333333333333337, 0.33333333333333337, 0.33333333333333337], [0.33333333333333337, 0.33333333333333337, 0.33333333333333337], [0.33333333333333337, 0.33333333333333337, 0.33333333333333337], [0.33333333333333337, 0.33333333333333337, 0.33333333333333337], [0.25, 0.25, 0.25, 0.25], [0.25, 0.25, 0.25, 0.25], [0.25, 0.25, 0.25, 0.25]]`.
If I choose the result[0] as the NE, and the result[0]['player1'] as the player1's mixed strategy as:
`[0.33333333333333337, 0.33333333333333337, 0.33333333333333337]`
in which player1 has 3 actions simply.

How to get each mix strategies in the form of numpy.array like:
`np.array([0.33333333333333337, 0.33333333333333337, 0.33333333333333337])`?

**Comment by tturocy** [comment]
When asking a question, it is very helpful (as requested in the documentation) to provide a runnable code sample that illustrates your problem.

Does not `np.array(result[0]['player1'])` return the result you expect?

**Comment by VitamintK** [comment]
Hi, I think I may be running into a similar issue, using pygambit 16.1.0 installed from pypi. I have a strategy `s` from `pygambit.nash.lp_solve`.

```
>>> type(s)
<class 'pygambit.gambit.MixedStrategy'>
>>> np.array(s)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "src/pygambit/mixed.pxi", line 57, in pygambit.gambit.MixedStrategy.__getitem__
  File "src/pygambit/mixed.pxi", line 113, in pygambit.gambit.MixedStrategyProfile.__getitem__
TypeError: profile index must be Player, Strategy, or str, not int
```

**Comment by VitamintK** [comment]
Ok, I'm assuming this is a bug? In case it is, I filed https://github.com/gambitproject/gambit/issues/430
