### ISSUE TITLE
bug: error when trying to convert strategy profile to list or array

### ISSUE THREAD

**Issue by VitamintK** [gambitproject/gambit#430]
In the documentation for 16.0.2 [link](https://gambitproject.readthedocs.io/en/v16.0.2/pyapi.html#mixed-strategy-and-behavior-profiles) there is this example:

```
In [1]: g = pygambit.Game.read_game("e02.nfg")

In [2]: p = g.mixed_strategy_profile()

In [3]: list(p)
Out[3]: [0.33333333333333331, 0.33333333333333331, 0.33333333333333331, 0.5, 0.5]
```

But when I try to run this on 16.1.0, I get an error:

```
>>> g = pygambit.Game.read_game("./e02.nfg")
>>> p = g.mixed_strategy_profile()
>>> list(p)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/pygambit/mixed.pxi", line 113, in pygambit.gambit.MixedStrategyProfile.__getitem__
TypeError: profile index must be Player, Strategy, or str, not int
```

I assume this is a bug.

**Comment by tturocy** [comment]
This behaviour is correct.  Mixed strategy and behaviour profiles are dict-like.  This is clarified in 16.1.0 and is the intended behaviour - you'll notice that the code quoted does not appear in the 16.1.0 docs.

**Comment by VitamintK** [comment]
@tturocy thanks for the quick response! What about mixed strategies (not mixed strategy profiles)? I was also unable to easily convert those to numpy arrays. Should there be an easy way to do that?

I didn't test the following code just now, but something like this was also erroring for me:
```
>>> g = pygambit.Game.read_game("./e02.nfg")
>>> p = g.mixed_strategy_profile()
>>> list(p[g.players[0]])
```

**Comment by tturocy** [comment]
Yes, use a list comprehension, a la the examples in the user's guide:

```
[p[s] for s in g.players[0].strategies]
```
