### ISSUE TITLE
BUG: Missing formats in `Game.write`

### ISSUE THREAD

**Issue by tturocy** [gambitproject/gambit#454]
The `Game.write` function documentation advertises that "efg" and "nfg" are valid options for the format; however, these are not implemented.

For "efg" this is maybe not that interesting, but for "nfg" it is somewhat relevant (if someone wanted to write out the strategic form of an extensive game, for some reason).

This applies to 16.1.x and 16.2.0.

**Comment by tturocy** [comment]
Here's our proposed plan for this:

[ ] Fix this in `maint16_1` for the next release of 16.1.
[ ] Merge that fix into `maint16_2` and `master`.
[ ] In 16.3, we will deprecate this in favour of the new functions we are going to develop as part of #357.
[ ] In 16.4, we will remove this function entirely.

**Comment by d-kad** [comment]
Let me double-check I get the task right: 

1) Do you mean we would completely get rid of the format “native” and replace it with “nfg”?
2) How do you see the functionality implemented - do we add branching for “nfg” both in the python function write() and in WriteGame()?

**Comment by tturocy** [comment]
We want to keep "native".  It's that "efg" and "nfg" are claimed by the documentation to work, and they do not!

I believe this should just be a matter of handling the "efg" and "nfg" options in the `WriteGame` wrapper function in `util.h`, as the corresponding C++ `Write` function on games is supposed to handle this.  But we need to check it does!
