### ISSUE TITLE
BUG: Handling end-of-file encountered in parsing numerical data in game files

### ISSUE THREAD

**Issue by bcollin3** [gambitproject/gambit#457]
If you call Game.parse_game() on a string that ends in a decimal utility value then the program will crash after a minute or two after consuming all of the system's ram.
For example:
```
import pygambit as gbt
s='NFG 1 R "prisoners dilemma"\n {"Player 1" "Player 2"} {2 2}\n -6 -6 -10 0 0 -10 -1 -1.0'
gbt.Game.parse_game(s)
```
will cause a crash but
```
import pygambit as gbt
s='NFG 1 R "prisoners dilemma"\n {"Player 1" "Player 2"} {2 2}\n -6 -6 -10 0 0 -10 -1 -1.0\n'
gbt.Game.parse_game(s)
```
will not.

**Comment by tturocy** [comment]
In `GameParserState::GetNextToken()` checks for the validity of the file after an attempted `.get()` are not done consistently, in particular in some places in which numerical data are parsed.
