### ISSUE TITLE
Check for valid values of path-following parameters in `logit_solve` and related functions

### ISSUE THREAD

**Issue by tturocy** [gambitproject/gambit#459]
We have recently exposed some of the algorithm parameters for controlling the numerical continuation in `logit_solve`, `logit_solve_lambda`, and `logit_solve_branch`.  At the moment these aren't being checked for being valid values.  The initial step length should be positive, and the acceleration factor should always be at least one.

**Comment by ankur-kalita** [comment]
heyy @tturocy can you assign this issue to me ?... i am working on it
